/*
 * sanity-tool bitreader service API
 * List of all endpoints used in API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ValueRefDto;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * InstructionDto
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-03-16T17:52:09.376Z")
public class InstructionDto {
  @SerializedName("kind")
  private String kind = null;

  @SerializedName("operands")
  private List<ValueRefDto> operands = null;

  @SerializedName("sourceRef")
  private Integer sourceRef = null;

  public InstructionDto kind(String kind) {
    this.kind = kind;
    return this;
  }

   /**
   * Get kind
   * @return kind
  **/
  @ApiModelProperty(value = "")
  public String getKind() {
    return kind;
  }

  public void setKind(String kind) {
    this.kind = kind;
  }

  public InstructionDto operands(List<ValueRefDto> operands) {
    this.operands = operands;
    return this;
  }

  public InstructionDto addOperandsItem(ValueRefDto operandsItem) {
    if (this.operands == null) {
      this.operands = new ArrayList<ValueRefDto>();
    }
    this.operands.add(operandsItem);
    return this;
  }

   /**
   * Get operands
   * @return operands
  **/
  @ApiModelProperty(value = "")
  public List<ValueRefDto> getOperands() {
    return operands;
  }

  public void setOperands(List<ValueRefDto> operands) {
    this.operands = operands;
  }

  public InstructionDto sourceRef(Integer sourceRef) {
    this.sourceRef = sourceRef;
    return this;
  }

   /**
   * Get sourceRef
   * @return sourceRef
  **/
  @ApiModelProperty(value = "")
  public Integer getSourceRef() {
    return sourceRef;
  }

  public void setSourceRef(Integer sourceRef) {
    this.sourceRef = sourceRef;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InstructionDto instructionDto = (InstructionDto) o;
    return Objects.equals(this.kind, instructionDto.kind) &&
        Objects.equals(this.operands, instructionDto.operands) &&
        Objects.equals(this.sourceRef, instructionDto.sourceRef);
  }

  @Override
  public int hashCode() {
    return Objects.hash(kind, operands, sourceRef);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InstructionDto {\n");
    
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    operands: ").append(toIndentedString(operands)).append("\n");
    sb.append("    sourceRef: ").append(toIndentedString(sourceRef)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

