/*
 * sanity-tool bitreader service API
 * List of all endpoints used in API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.FunctionDto;
import io.swagger.client.model.SourceRefDto;
import io.swagger.client.model.TypeDto;
import io.swagger.client.model.ValueDto;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ModuleDto
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-03-16T17:52:09.376Z")
public class ModuleDto {
  @SerializedName("functions")
  private List<FunctionDto> functions = null;

  @SerializedName("globals")
  private List<ValueDto> globals = null;

  @SerializedName("sourceRefs")
  private List<SourceRefDto> sourceRefs = null;

  @SerializedName("types")
  private List<TypeDto> types = null;

  public ModuleDto functions(List<FunctionDto> functions) {
    this.functions = functions;
    return this;
  }

  public ModuleDto addFunctionsItem(FunctionDto functionsItem) {
    if (this.functions == null) {
      this.functions = new ArrayList<FunctionDto>();
    }
    this.functions.add(functionsItem);
    return this;
  }

   /**
   * Get functions
   * @return functions
  **/
  @ApiModelProperty(value = "")
  public List<FunctionDto> getFunctions() {
    return functions;
  }

  public void setFunctions(List<FunctionDto> functions) {
    this.functions = functions;
  }

  public ModuleDto globals(List<ValueDto> globals) {
    this.globals = globals;
    return this;
  }

  public ModuleDto addGlobalsItem(ValueDto globalsItem) {
    if (this.globals == null) {
      this.globals = new ArrayList<ValueDto>();
    }
    this.globals.add(globalsItem);
    return this;
  }

   /**
   * Get globals
   * @return globals
  **/
  @ApiModelProperty(value = "")
  public List<ValueDto> getGlobals() {
    return globals;
  }

  public void setGlobals(List<ValueDto> globals) {
    this.globals = globals;
  }

  public ModuleDto sourceRefs(List<SourceRefDto> sourceRefs) {
    this.sourceRefs = sourceRefs;
    return this;
  }

  public ModuleDto addSourceRefsItem(SourceRefDto sourceRefsItem) {
    if (this.sourceRefs == null) {
      this.sourceRefs = new ArrayList<SourceRefDto>();
    }
    this.sourceRefs.add(sourceRefsItem);
    return this;
  }

   /**
   * Get sourceRefs
   * @return sourceRefs
  **/
  @ApiModelProperty(value = "")
  public List<SourceRefDto> getSourceRefs() {
    return sourceRefs;
  }

  public void setSourceRefs(List<SourceRefDto> sourceRefs) {
    this.sourceRefs = sourceRefs;
  }

  public ModuleDto types(List<TypeDto> types) {
    this.types = types;
    return this;
  }

  public ModuleDto addTypesItem(TypeDto typesItem) {
    if (this.types == null) {
      this.types = new ArrayList<TypeDto>();
    }
    this.types.add(typesItem);
    return this;
  }

   /**
   * Get types
   * @return types
  **/
  @ApiModelProperty(value = "")
  public List<TypeDto> getTypes() {
    return types;
  }

  public void setTypes(List<TypeDto> types) {
    this.types = types;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModuleDto moduleDto = (ModuleDto) o;
    return Objects.equals(this.functions, moduleDto.functions) &&
        Objects.equals(this.globals, moduleDto.globals) &&
        Objects.equals(this.sourceRefs, moduleDto.sourceRefs) &&
        Objects.equals(this.types, moduleDto.types);
  }

  @Override
  public int hashCode() {
    return Objects.hash(functions, globals, sourceRefs, types);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModuleDto {\n");
    
    sb.append("    functions: ").append(toIndentedString(functions)).append("\n");
    sb.append("    globals: ").append(toIndentedString(globals)).append("\n");
    sb.append("    sourceRefs: ").append(toIndentedString(sourceRefs)).append("\n");
    sb.append("    types: ").append(toIndentedString(types)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

