/*
 * sanity-tool bitreader service API
 * List of all endpoints used in API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ValueRefDto;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ValueDto
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-03-16T17:52:09.376Z")
public class ValueDto {
  @SerializedName("fpValue")
  private Double fpValue = null;

  @SerializedName("intValue")
  private Long intValue = null;

  @SerializedName("kind")
  private String kind = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("opcode")
  private String opcode = null;

  @SerializedName("operands")
  private List<ValueRefDto> operands = null;

  @SerializedName("typeId")
  private Integer typeId = null;

  public ValueDto fpValue(Double fpValue) {
    this.fpValue = fpValue;
    return this;
  }

   /**
   * Get fpValue
   * @return fpValue
  **/
  @ApiModelProperty(value = "")
  public Double getFpValue() {
    return fpValue;
  }

  public void setFpValue(Double fpValue) {
    this.fpValue = fpValue;
  }

  public ValueDto intValue(Long intValue) {
    this.intValue = intValue;
    return this;
  }

   /**
   * Get intValue
   * @return intValue
  **/
  @ApiModelProperty(value = "")
  public Long getIntValue() {
    return intValue;
  }

  public void setIntValue(Long intValue) {
    this.intValue = intValue;
  }

  public ValueDto kind(String kind) {
    this.kind = kind;
    return this;
  }

   /**
   * Get kind
   * @return kind
  **/
  @ApiModelProperty(value = "")
  public String getKind() {
    return kind;
  }

  public void setKind(String kind) {
    this.kind = kind;
  }

  public ValueDto name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ValueDto opcode(String opcode) {
    this.opcode = opcode;
    return this;
  }

   /**
   * Get opcode
   * @return opcode
  **/
  @ApiModelProperty(value = "")
  public String getOpcode() {
    return opcode;
  }

  public void setOpcode(String opcode) {
    this.opcode = opcode;
  }

  public ValueDto operands(List<ValueRefDto> operands) {
    this.operands = operands;
    return this;
  }

  public ValueDto addOperandsItem(ValueRefDto operandsItem) {
    if (this.operands == null) {
      this.operands = new ArrayList<ValueRefDto>();
    }
    this.operands.add(operandsItem);
    return this;
  }

   /**
   * Get operands
   * @return operands
  **/
  @ApiModelProperty(value = "")
  public List<ValueRefDto> getOperands() {
    return operands;
  }

  public void setOperands(List<ValueRefDto> operands) {
    this.operands = operands;
  }

  public ValueDto typeId(Integer typeId) {
    this.typeId = typeId;
    return this;
  }

   /**
   * Get typeId
   * @return typeId
  **/
  @ApiModelProperty(value = "")
  public Integer getTypeId() {
    return typeId;
  }

  public void setTypeId(Integer typeId) {
    this.typeId = typeId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ValueDto valueDto = (ValueDto) o;
    return Objects.equals(this.fpValue, valueDto.fpValue) &&
        Objects.equals(this.intValue, valueDto.intValue) &&
        Objects.equals(this.kind, valueDto.kind) &&
        Objects.equals(this.name, valueDto.name) &&
        Objects.equals(this.opcode, valueDto.opcode) &&
        Objects.equals(this.operands, valueDto.operands) &&
        Objects.equals(this.typeId, valueDto.typeId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fpValue, intValue, kind, name, opcode, operands, typeId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ValueDto {\n");
    
    sb.append("    fpValue: ").append(toIndentedString(fpValue)).append("\n");
    sb.append("    intValue: ").append(toIndentedString(intValue)).append("\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    opcode: ").append(toIndentedString(opcode)).append("\n");
    sb.append("    operands: ").append(toIndentedString(operands)).append("\n");
    sb.append("    typeId: ").append(toIndentedString(typeId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

