/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package na.okutane.cpp.llvm;

public class AllocaInst {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected AllocaInst(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AllocaInst obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bitreaderJNI.delete_AllocaInst(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public AllocaInst(Type Ty, Value ArraySize, SWIGTYPE_p_llvm__Twine Name, Instruction InsertBefore) {
    this(bitreaderJNI.new_AllocaInst__SWIG_0(Type.getCPtr(Ty), Ty, Value.getCPtr(ArraySize), ArraySize, SWIGTYPE_p_llvm__Twine.getCPtr(Name), Instruction.getCPtr(InsertBefore), InsertBefore), true);
  }

  public AllocaInst(Type Ty, Value ArraySize, SWIGTYPE_p_llvm__Twine Name) {
    this(bitreaderJNI.new_AllocaInst__SWIG_1(Type.getCPtr(Ty), Ty, Value.getCPtr(ArraySize), ArraySize, SWIGTYPE_p_llvm__Twine.getCPtr(Name)), true);
  }

  public AllocaInst(Type Ty, Value ArraySize) {
    this(bitreaderJNI.new_AllocaInst__SWIG_2(Type.getCPtr(Ty), Ty, Value.getCPtr(ArraySize), ArraySize), true);
  }

  public AllocaInst(Type Ty) {
    this(bitreaderJNI.new_AllocaInst__SWIG_3(Type.getCPtr(Ty), Ty), true);
  }

  public AllocaInst(Type Ty, Value ArraySize, SWIGTYPE_p_llvm__Twine Name, BasicBlock InsertAtEnd) {
    this(bitreaderJNI.new_AllocaInst__SWIG_4(Type.getCPtr(Ty), Ty, Value.getCPtr(ArraySize), ArraySize, SWIGTYPE_p_llvm__Twine.getCPtr(Name), BasicBlock.getCPtr(InsertAtEnd), InsertAtEnd), true);
  }

  public AllocaInst(Type Ty, SWIGTYPE_p_llvm__Twine Name, Instruction InsertBefore) {
    this(bitreaderJNI.new_AllocaInst__SWIG_5(Type.getCPtr(Ty), Ty, SWIGTYPE_p_llvm__Twine.getCPtr(Name), Instruction.getCPtr(InsertBefore), InsertBefore), true);
  }

  public AllocaInst(Type Ty, SWIGTYPE_p_llvm__Twine Name) {
    this(bitreaderJNI.new_AllocaInst__SWIG_6(Type.getCPtr(Ty), Ty, SWIGTYPE_p_llvm__Twine.getCPtr(Name)), true);
  }

  public AllocaInst(Type Ty, SWIGTYPE_p_llvm__Twine Name, BasicBlock InsertAtEnd) {
    this(bitreaderJNI.new_AllocaInst__SWIG_7(Type.getCPtr(Ty), Ty, SWIGTYPE_p_llvm__Twine.getCPtr(Name), BasicBlock.getCPtr(InsertAtEnd), InsertAtEnd), true);
  }

  public AllocaInst(Type Ty, Value ArraySize, long Align, SWIGTYPE_p_llvm__Twine Name, Instruction InsertBefore) {
    this(bitreaderJNI.new_AllocaInst__SWIG_8(Type.getCPtr(Ty), Ty, Value.getCPtr(ArraySize), ArraySize, Align, SWIGTYPE_p_llvm__Twine.getCPtr(Name), Instruction.getCPtr(InsertBefore), InsertBefore), true);
  }

  public AllocaInst(Type Ty, Value ArraySize, long Align, SWIGTYPE_p_llvm__Twine Name) {
    this(bitreaderJNI.new_AllocaInst__SWIG_9(Type.getCPtr(Ty), Ty, Value.getCPtr(ArraySize), ArraySize, Align, SWIGTYPE_p_llvm__Twine.getCPtr(Name)), true);
  }

  public AllocaInst(Type Ty, Value ArraySize, long Align) {
    this(bitreaderJNI.new_AllocaInst__SWIG_10(Type.getCPtr(Ty), Ty, Value.getCPtr(ArraySize), ArraySize, Align), true);
  }

  public AllocaInst(Type Ty, Value ArraySize, long Align, SWIGTYPE_p_llvm__Twine Name, BasicBlock InsertAtEnd) {
    this(bitreaderJNI.new_AllocaInst__SWIG_11(Type.getCPtr(Ty), Ty, Value.getCPtr(ArraySize), ArraySize, Align, SWIGTYPE_p_llvm__Twine.getCPtr(Name), BasicBlock.getCPtr(InsertAtEnd), InsertAtEnd), true);
  }

  public boolean isArrayAllocation() {
    return bitreaderJNI.AllocaInst_isArrayAllocation(swigCPtr, this);
  }

  public Value getArraySize() {
    long cPtr = bitreaderJNI.AllocaInst_getArraySize__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new Value(cPtr, false);
  }

  public SWIGTYPE_p_llvm__PointerType getType() {
    long cPtr = bitreaderJNI.AllocaInst_getType(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_llvm__PointerType(cPtr, false);
  }

  public Type getAllocatedType() {
    long cPtr = bitreaderJNI.AllocaInst_getAllocatedType(swigCPtr, this);
    return (cPtr == 0) ? null : new Type(cPtr, false);
  }

  public long getAlignment() {
    return bitreaderJNI.AllocaInst_getAlignment(swigCPtr, this);
  }

  public void setAlignment(long Align) {
    bitreaderJNI.AllocaInst_setAlignment(swigCPtr, this, Align);
  }

  public boolean isStaticAlloca() {
    return bitreaderJNI.AllocaInst_isStaticAlloca(swigCPtr, this);
  }

  public static boolean classof(Instruction I) {
    return bitreaderJNI.AllocaInst_classof__SWIG_0(Instruction.getCPtr(I), I);
  }

  public static boolean classof(Value V) {
    return bitreaderJNI.AllocaInst_classof__SWIG_1(Value.getCPtr(V), V);
  }

}
