/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package na.okutane.cpp.llvm;

public class AtomicCmpXchgInst extends Instruction {
  private long swigCPtr;

  protected AtomicCmpXchgInst(long cPtr, boolean cMemoryOwn) {
    super(bitreaderJNI.AtomicCmpXchgInst_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AtomicCmpXchgInst obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bitreaderJNI.delete_AtomicCmpXchgInst(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public boolean isVolatile() {
    return bitreaderJNI.AtomicCmpXchgInst_isVolatile(swigCPtr, this);
  }

  public void setVolatile(boolean V) {
    bitreaderJNI.AtomicCmpXchgInst_setVolatile(swigCPtr, this, V);
  }

  public void setOrdering(AtomicOrdering Ordering) {
    bitreaderJNI.AtomicCmpXchgInst_setOrdering(swigCPtr, this, Ordering.swigValue());
  }

  public void setSynchScope(SynchronizationScope SynchScope) {
    bitreaderJNI.AtomicCmpXchgInst_setSynchScope(swigCPtr, this, SynchScope.swigValue());
  }

  public AtomicOrdering getOrdering() {
    return AtomicOrdering.swigToEnum(bitreaderJNI.AtomicCmpXchgInst_getOrdering(swigCPtr, this));
  }

  public SynchronizationScope getSynchScope() {
    return SynchronizationScope.swigToEnum(bitreaderJNI.AtomicCmpXchgInst_getSynchScope(swigCPtr, this));
  }

  public Value getPointerOperand() {
    long cPtr = bitreaderJNI.AtomicCmpXchgInst_getPointerOperand__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new Value(cPtr, false);
  }

  public static long getPointerOperandIndex() {
    return bitreaderJNI.AtomicCmpXchgInst_getPointerOperandIndex();
  }

  public Value getCompareOperand() {
    long cPtr = bitreaderJNI.AtomicCmpXchgInst_getCompareOperand__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new Value(cPtr, false);
  }

  public Value getNewValOperand() {
    long cPtr = bitreaderJNI.AtomicCmpXchgInst_getNewValOperand__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new Value(cPtr, false);
  }

  public long getPointerAddressSpace() {
    return bitreaderJNI.AtomicCmpXchgInst_getPointerAddressSpace(swigCPtr, this);
  }

  public static boolean classof(Instruction I) {
    return bitreaderJNI.AtomicCmpXchgInst_classof__SWIG_0(Instruction.getCPtr(I), I);
  }

  public static boolean classof(Value V) {
    return bitreaderJNI.AtomicCmpXchgInst_classof__SWIG_1(Value.getCPtr(V), V);
  }

}
