/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package na.okutane.cpp.llvm;

public class BasicBlock extends Value {
  private long swigCPtr;

  protected BasicBlock(long cPtr, boolean cMemoryOwn) {
    super(bitreaderJNI.BasicBlock_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BasicBlock obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bitreaderJNI.delete_BasicBlock(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public LLVMContext getContext() {
    return new LLVMContext(bitreaderJNI.BasicBlock_getContext(swigCPtr, this), false);
  }

  public static BasicBlock Create(LLVMContext Context, SWIGTYPE_p_llvm__Twine Name, Function Parent, BasicBlock InsertBefore) {
    long cPtr = bitreaderJNI.BasicBlock_Create__SWIG_0(LLVMContext.getCPtr(Context), Context, SWIGTYPE_p_llvm__Twine.getCPtr(Name), Function.getCPtr(Parent), Parent, BasicBlock.getCPtr(InsertBefore), InsertBefore);
    return (cPtr == 0) ? null : new BasicBlock(cPtr, false);
  }

  public static BasicBlock Create(LLVMContext Context, SWIGTYPE_p_llvm__Twine Name, Function Parent) {
    long cPtr = bitreaderJNI.BasicBlock_Create__SWIG_1(LLVMContext.getCPtr(Context), Context, SWIGTYPE_p_llvm__Twine.getCPtr(Name), Function.getCPtr(Parent), Parent);
    return (cPtr == 0) ? null : new BasicBlock(cPtr, false);
  }

  public static BasicBlock Create(LLVMContext Context, SWIGTYPE_p_llvm__Twine Name) {
    long cPtr = bitreaderJNI.BasicBlock_Create__SWIG_2(LLVMContext.getCPtr(Context), Context, SWIGTYPE_p_llvm__Twine.getCPtr(Name));
    return (cPtr == 0) ? null : new BasicBlock(cPtr, false);
  }

  public static BasicBlock Create(LLVMContext Context) {
    long cPtr = bitreaderJNI.BasicBlock_Create__SWIG_3(LLVMContext.getCPtr(Context), Context);
    return (cPtr == 0) ? null : new BasicBlock(cPtr, false);
  }

  public Function getParent() {
    long cPtr = bitreaderJNI.BasicBlock_getParent__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new Function(cPtr, false);
  }

  public SWIGTYPE_p_llvm__TerminatorInst getTerminator() {
    long cPtr = bitreaderJNI.BasicBlock_getTerminator__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_llvm__TerminatorInst(cPtr, false);
  }

  public Instruction getFirstNonPHI() {
    long cPtr = bitreaderJNI.BasicBlock_getFirstNonPHI__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new Instruction(cPtr, false);
  }

  public Instruction getFirstNonPHIOrDbg() {
    long cPtr = bitreaderJNI.BasicBlock_getFirstNonPHIOrDbg__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new Instruction(cPtr, false);
  }

  public Instruction getFirstNonPHIOrDbgOrLifetime() {
    long cPtr = bitreaderJNI.BasicBlock_getFirstNonPHIOrDbgOrLifetime__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new Instruction(cPtr, false);
  }

  public SWIGTYPE_p_llvm__iplistT_llvm__Instruction_t__iterator getFirstInsertionPt() {
    return new SWIGTYPE_p_llvm__iplistT_llvm__Instruction_t__iterator(bitreaderJNI.BasicBlock_getFirstInsertionPt__SWIG_0(swigCPtr, this), true);
  }

  public void removeFromParent() {
    bitreaderJNI.BasicBlock_removeFromParent(swigCPtr, this);
  }

  public void eraseFromParent() {
    bitreaderJNI.BasicBlock_eraseFromParent(swigCPtr, this);
  }

  public void moveBefore(BasicBlock MovePos) {
    bitreaderJNI.BasicBlock_moveBefore(swigCPtr, this, BasicBlock.getCPtr(MovePos), MovePos);
  }

  public void moveAfter(BasicBlock MovePos) {
    bitreaderJNI.BasicBlock_moveAfter(swigCPtr, this, BasicBlock.getCPtr(MovePos), MovePos);
  }

  public BasicBlock getSinglePredecessor() {
    long cPtr = bitreaderJNI.BasicBlock_getSinglePredecessor__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new BasicBlock(cPtr, false);
  }

  public BasicBlock getUniquePredecessor() {
    long cPtr = bitreaderJNI.BasicBlock_getUniquePredecessor__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new BasicBlock(cPtr, false);
  }

  public SWIGTYPE_p_llvm__iplistT_llvm__Instruction_t__iterator begin() {
    return new SWIGTYPE_p_llvm__iplistT_llvm__Instruction_t__iterator(bitreaderJNI.BasicBlock_begin__SWIG_0(swigCPtr, this), true);
  }

  public SWIGTYPE_p_llvm__iplistT_llvm__Instruction_t__iterator end() {
    return new SWIGTYPE_p_llvm__iplistT_llvm__Instruction_t__iterator(bitreaderJNI.BasicBlock_end__SWIG_0(swigCPtr, this), true);
  }

  public SWIGTYPE_p_llvm__iplistT_llvm__Instruction_t__reverse_iterator rbegin() {
    return new SWIGTYPE_p_llvm__iplistT_llvm__Instruction_t__reverse_iterator(bitreaderJNI.BasicBlock_rbegin__SWIG_0(swigCPtr, this), true);
  }

  public SWIGTYPE_p_llvm__iplistT_llvm__Instruction_t__reverse_iterator rend() {
    return new SWIGTYPE_p_llvm__iplistT_llvm__Instruction_t__reverse_iterator(bitreaderJNI.BasicBlock_rend__SWIG_0(swigCPtr, this), true);
  }

  public long size() {
    return bitreaderJNI.BasicBlock_size(swigCPtr, this);
  }

  public boolean empty() {
    return bitreaderJNI.BasicBlock_empty(swigCPtr, this);
  }

  public Instruction front() {
    return new Instruction(bitreaderJNI.BasicBlock_front__SWIG_0(swigCPtr, this), false);
  }

  public Instruction back() {
    return new Instruction(bitreaderJNI.BasicBlock_back__SWIG_0(swigCPtr, this), false);
  }

  public SWIGTYPE_p_llvm__iplistT_llvm__Instruction_t getInstList() {
    return new SWIGTYPE_p_llvm__iplistT_llvm__Instruction_t(bitreaderJNI.BasicBlock_getInstList__SWIG_0(swigCPtr, this), false);
  }

  public static SWIGTYPE_m_BasicBlock__llvm__iplistT_llvm__Instruction_t getSublistAccess(Instruction arg0) {
    String cMemberPtr = bitreaderJNI.BasicBlock_getSublistAccess(Instruction.getCPtr(arg0), arg0);
    return (cMemberPtr == null) ? null : new SWIGTYPE_m_BasicBlock__llvm__iplistT_llvm__Instruction_t(cMemberPtr, false);
  }

  public SWIGTYPE_p_llvm__ValueSymbolTable getValueSymbolTable() {
    long cPtr = bitreaderJNI.BasicBlock_getValueSymbolTable(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_llvm__ValueSymbolTable(cPtr, false);
  }

  public static boolean classof(Value V) {
    return bitreaderJNI.BasicBlock_classof(Value.getCPtr(V), V);
  }

  public void dropAllReferences() {
    bitreaderJNI.BasicBlock_dropAllReferences(swigCPtr, this);
  }

  public void removePredecessor(BasicBlock Pred, boolean DontDeleteUselessPHIs) {
    bitreaderJNI.BasicBlock_removePredecessor__SWIG_0(swigCPtr, this, BasicBlock.getCPtr(Pred), Pred, DontDeleteUselessPHIs);
  }

  public void removePredecessor(BasicBlock Pred) {
    bitreaderJNI.BasicBlock_removePredecessor__SWIG_1(swigCPtr, this, BasicBlock.getCPtr(Pred), Pred);
  }

  public BasicBlock splitBasicBlock(SWIGTYPE_p_llvm__iplistT_llvm__Instruction_t__iterator I, SWIGTYPE_p_llvm__Twine BBName) {
    long cPtr = bitreaderJNI.BasicBlock_splitBasicBlock__SWIG_0(swigCPtr, this, SWIGTYPE_p_llvm__iplistT_llvm__Instruction_t__iterator.getCPtr(I), SWIGTYPE_p_llvm__Twine.getCPtr(BBName));
    return (cPtr == 0) ? null : new BasicBlock(cPtr, false);
  }

  public BasicBlock splitBasicBlock(SWIGTYPE_p_llvm__iplistT_llvm__Instruction_t__iterator I) {
    long cPtr = bitreaderJNI.BasicBlock_splitBasicBlock__SWIG_1(swigCPtr, this, SWIGTYPE_p_llvm__iplistT_llvm__Instruction_t__iterator.getCPtr(I));
    return (cPtr == 0) ? null : new BasicBlock(cPtr, false);
  }

  public boolean hasAddressTaken() {
    return bitreaderJNI.BasicBlock_hasAddressTaken(swigCPtr, this);
  }

  public void replaceSuccessorsPhiUsesWith(BasicBlock New) {
    bitreaderJNI.BasicBlock_replaceSuccessorsPhiUsesWith(swigCPtr, this, BasicBlock.getCPtr(New), New);
  }

  public boolean isLandingPad() {
    return bitreaderJNI.BasicBlock_isLandingPad(swigCPtr, this);
  }

  public LandingPadInst getLandingPadInst() {
    long cPtr = bitreaderJNI.BasicBlock_getLandingPadInst__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new LandingPadInst(cPtr, false);
  }

}
