/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package na.okutane.cpp.llvm;

public class bitreader {
  public static LLVMContext getGlobalContext() {
    return new LLVMContext(bitreaderJNI.getGlobalContext(), false);
  }

  public static SWIGTYPE_p_p_llvm__LLVMContext unwrap(SWIGTYPE_p_LLVMContextRef Tys) {
    long cPtr = bitreaderJNI.unwrap__SWIG_0(SWIGTYPE_p_LLVMContextRef.getCPtr(Tys));
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_llvm__LLVMContext(cPtr, false);
  }

  public static SWIGTYPE_p_LLVMContextRef wrap(SWIGTYPE_p_p_llvm__LLVMContext Tys) {
    long cPtr = bitreaderJNI.wrap(SWIGTYPE_p_p_llvm__LLVMContext.getCPtr(Tys));
    return (cPtr == 0) ? null : new SWIGTYPE_p_LLVMContextRef(cPtr, false);
  }

  public static Module unwrap(SWIGTYPE_p_LLVMModuleProviderRef MP) {
    long cPtr = bitreaderJNI.unwrap__SWIG_1(SWIGTYPE_p_LLVMModuleProviderRef.getCPtr(MP));
    return (cPtr == 0) ? null : new Module(cPtr, false);
  }

  public static Module getLazyIRModule(SWIGTYPE_p_llvm__MemoryBuffer Buffer, SWIGTYPE_p_llvm__SMDiagnostic Err, LLVMContext Context) {
    long cPtr = bitreaderJNI.getLazyIRModule(SWIGTYPE_p_llvm__MemoryBuffer.getCPtr(Buffer), SWIGTYPE_p_llvm__SMDiagnostic.getCPtr(Err), LLVMContext.getCPtr(Context), Context);
    return (cPtr == 0) ? null : new Module(cPtr, false);
  }

  public static Module getLazyIRFileModule(SWIGTYPE_p_std__string Filename, SWIGTYPE_p_llvm__SMDiagnostic Err, LLVMContext Context) {
    long cPtr = bitreaderJNI.getLazyIRFileModule(SWIGTYPE_p_std__string.getCPtr(Filename), SWIGTYPE_p_llvm__SMDiagnostic.getCPtr(Err), LLVMContext.getCPtr(Context), Context);
    return (cPtr == 0) ? null : new Module(cPtr, false);
  }

  public static Module ParseIR(SWIGTYPE_p_llvm__MemoryBuffer Buffer, SWIGTYPE_p_llvm__SMDiagnostic Err, LLVMContext Context) {
    long cPtr = bitreaderJNI.ParseIR(SWIGTYPE_p_llvm__MemoryBuffer.getCPtr(Buffer), SWIGTYPE_p_llvm__SMDiagnostic.getCPtr(Err), LLVMContext.getCPtr(Context), Context);
    return (cPtr == 0) ? null : new Module(cPtr, false);
  }

  public static Module ParseIRFile(SWIGTYPE_p_std__string Filename, SWIGTYPE_p_llvm__SMDiagnostic Err, LLVMContext Context) {
    long cPtr = bitreaderJNI.ParseIRFile(SWIGTYPE_p_std__string.getCPtr(Filename), SWIGTYPE_p_llvm__SMDiagnostic.getCPtr(Err), LLVMContext.getCPtr(Context), Context);
    return (cPtr == 0) ? null : new Module(cPtr, false);
  }

  public static Module parse(String filename) {
    long cPtr = bitreaderJNI.parse(filename);
    return (cPtr == 0) ? null : new Module(cPtr, false);
  }

}
