/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package na.okutane.cpp.llvm;

public class ConstantAggregateZero extends Constant {
  private long swigCPtr;

  protected ConstantAggregateZero(long cPtr, boolean cMemoryOwn) {
    super(bitreaderJNI.ConstantAggregateZero_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ConstantAggregateZero obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bitreaderJNI.delete_ConstantAggregateZero(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static ConstantAggregateZero get(Type Ty) {
    long cPtr = bitreaderJNI.ConstantAggregateZero_get(Type.getCPtr(Ty), Ty);
    return (cPtr == 0) ? null : new ConstantAggregateZero(cPtr, false);
  }

  public void destroyConstant() {
    bitreaderJNI.ConstantAggregateZero_destroyConstant(swigCPtr, this);
  }

  public Constant getSequentialElement() {
    long cPtr = bitreaderJNI.ConstantAggregateZero_getSequentialElement(swigCPtr, this);
    return (cPtr == 0) ? null : new Constant(cPtr, false);
  }

  public Constant getStructElement(long Elt) {
    long cPtr = bitreaderJNI.ConstantAggregateZero_getStructElement(swigCPtr, this, Elt);
    return (cPtr == 0) ? null : new Constant(cPtr, false);
  }

  public Constant getElementValue(Constant C) {
    long cPtr = bitreaderJNI.ConstantAggregateZero_getElementValue__SWIG_0(swigCPtr, this, Constant.getCPtr(C), C);
    return (cPtr == 0) ? null : new Constant(cPtr, false);
  }

  public Constant getElementValue(long Idx) {
    long cPtr = bitreaderJNI.ConstantAggregateZero_getElementValue__SWIG_1(swigCPtr, this, Idx);
    return (cPtr == 0) ? null : new Constant(cPtr, false);
  }

  public static boolean classof(Value V) {
    return bitreaderJNI.ConstantAggregateZero_classof(Value.getCPtr(V), V);
  }

}
