/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package na.okutane.cpp.llvm;

public class ConstantDataVector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ConstantDataVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ConstantDataVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bitreaderJNI.delete_ConstantDataVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static Constant get(LLVMContext Context, SWIGTYPE_p_ArrayRefT_uint8_t_t Elts) {
    long cPtr = bitreaderJNI.ConstantDataVector_get__SWIG_0(LLVMContext.getCPtr(Context), Context, SWIGTYPE_p_ArrayRefT_uint8_t_t.getCPtr(Elts));
    return (cPtr == 0) ? null : new Constant(cPtr, false);
  }

  public static Constant get(LLVMContext Context, SWIGTYPE_p_ArrayRefT_uint16_t_t Elts) {
    long cPtr = bitreaderJNI.ConstantDataVector_get__SWIG_1(LLVMContext.getCPtr(Context), Context, SWIGTYPE_p_ArrayRefT_uint16_t_t.getCPtr(Elts));
    return (cPtr == 0) ? null : new Constant(cPtr, false);
  }

  public static Constant get(LLVMContext Context, SWIGTYPE_p_ArrayRefT_uint32_t_t Elts) {
    long cPtr = bitreaderJNI.ConstantDataVector_get__SWIG_2(LLVMContext.getCPtr(Context), Context, SWIGTYPE_p_ArrayRefT_uint32_t_t.getCPtr(Elts));
    return (cPtr == 0) ? null : new Constant(cPtr, false);
  }

  public static Constant get(LLVMContext Context, SWIGTYPE_p_ArrayRefT_uint64_t_t Elts) {
    long cPtr = bitreaderJNI.ConstantDataVector_get__SWIG_3(LLVMContext.getCPtr(Context), Context, SWIGTYPE_p_ArrayRefT_uint64_t_t.getCPtr(Elts));
    return (cPtr == 0) ? null : new Constant(cPtr, false);
  }

  public static Constant get(LLVMContext Context, SWIGTYPE_p_ArrayRefT_float_t Elts) {
    long cPtr = bitreaderJNI.ConstantDataVector_get__SWIG_4(LLVMContext.getCPtr(Context), Context, SWIGTYPE_p_ArrayRefT_float_t.getCPtr(Elts));
    return (cPtr == 0) ? null : new Constant(cPtr, false);
  }

  public static Constant get(LLVMContext Context, SWIGTYPE_p_ArrayRefT_double_t Elts) {
    long cPtr = bitreaderJNI.ConstantDataVector_get__SWIG_5(LLVMContext.getCPtr(Context), Context, SWIGTYPE_p_ArrayRefT_double_t.getCPtr(Elts));
    return (cPtr == 0) ? null : new Constant(cPtr, false);
  }

  public static Constant getSplat(long NumElts, Constant Elt) {
    long cPtr = bitreaderJNI.ConstantDataVector_getSplat(NumElts, Constant.getCPtr(Elt), Elt);
    return (cPtr == 0) ? null : new Constant(cPtr, false);
  }

  public Constant getSplatValue() {
    long cPtr = bitreaderJNI.ConstantDataVector_getSplatValue(swigCPtr, this);
    return (cPtr == 0) ? null : new Constant(cPtr, false);
  }

  public SWIGTYPE_p_llvm__VectorType getType() {
    long cPtr = bitreaderJNI.ConstantDataVector_getType(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_llvm__VectorType(cPtr, false);
  }

  public static boolean classof(Value V) {
    return bitreaderJNI.ConstantDataVector_classof(Value.getCPtr(V), V);
  }

}
