/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package na.okutane.cpp.llvm;

public class ConstantStruct extends Constant {
  private long swigCPtr;

  protected ConstantStruct(long cPtr, boolean cMemoryOwn) {
    super(bitreaderJNI.ConstantStruct_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ConstantStruct obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bitreaderJNI.delete_ConstantStruct(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static Constant get(SWIGTYPE_p_llvm__StructType T, SWIGTYPE_p_ArrayRefT_llvm__Constant_p_t V) {
    long cPtr = bitreaderJNI.ConstantStruct_get__SWIG_0(SWIGTYPE_p_llvm__StructType.getCPtr(T), SWIGTYPE_p_ArrayRefT_llvm__Constant_p_t.getCPtr(V));
    return (cPtr == 0) ? null : new Constant(cPtr, false);
  }

  public static Constant get(SWIGTYPE_p_llvm__StructType T) {
    long cPtr = bitreaderJNI.ConstantStruct_get__SWIG_1(SWIGTYPE_p_llvm__StructType.getCPtr(T));
    return (cPtr == 0) ? null : new Constant(cPtr, false);
  }

  public static Constant getAnon(SWIGTYPE_p_ArrayRefT_llvm__Constant_p_t V, boolean Packed) {
    long cPtr = bitreaderJNI.ConstantStruct_getAnon__SWIG_0(SWIGTYPE_p_ArrayRefT_llvm__Constant_p_t.getCPtr(V), Packed);
    return (cPtr == 0) ? null : new Constant(cPtr, false);
  }

  public static Constant getAnon(SWIGTYPE_p_ArrayRefT_llvm__Constant_p_t V) {
    long cPtr = bitreaderJNI.ConstantStruct_getAnon__SWIG_1(SWIGTYPE_p_ArrayRefT_llvm__Constant_p_t.getCPtr(V));
    return (cPtr == 0) ? null : new Constant(cPtr, false);
  }

  public static Constant getAnon(LLVMContext Ctx, SWIGTYPE_p_ArrayRefT_llvm__Constant_p_t V, boolean Packed) {
    long cPtr = bitreaderJNI.ConstantStruct_getAnon__SWIG_2(LLVMContext.getCPtr(Ctx), Ctx, SWIGTYPE_p_ArrayRefT_llvm__Constant_p_t.getCPtr(V), Packed);
    return (cPtr == 0) ? null : new Constant(cPtr, false);
  }

  public static Constant getAnon(LLVMContext Ctx, SWIGTYPE_p_ArrayRefT_llvm__Constant_p_t V) {
    long cPtr = bitreaderJNI.ConstantStruct_getAnon__SWIG_3(LLVMContext.getCPtr(Ctx), Ctx, SWIGTYPE_p_ArrayRefT_llvm__Constant_p_t.getCPtr(V));
    return (cPtr == 0) ? null : new Constant(cPtr, false);
  }

  public static SWIGTYPE_p_llvm__StructType getTypeForElements(SWIGTYPE_p_ArrayRefT_llvm__Constant_p_t V, boolean Packed) {
    long cPtr = bitreaderJNI.ConstantStruct_getTypeForElements__SWIG_0(SWIGTYPE_p_ArrayRefT_llvm__Constant_p_t.getCPtr(V), Packed);
    return (cPtr == 0) ? null : new SWIGTYPE_p_llvm__StructType(cPtr, false);
  }

  public static SWIGTYPE_p_llvm__StructType getTypeForElements(SWIGTYPE_p_ArrayRefT_llvm__Constant_p_t V) {
    long cPtr = bitreaderJNI.ConstantStruct_getTypeForElements__SWIG_1(SWIGTYPE_p_ArrayRefT_llvm__Constant_p_t.getCPtr(V));
    return (cPtr == 0) ? null : new SWIGTYPE_p_llvm__StructType(cPtr, false);
  }

  public static SWIGTYPE_p_llvm__StructType getTypeForElements(LLVMContext Ctx, SWIGTYPE_p_ArrayRefT_llvm__Constant_p_t V, boolean Packed) {
    long cPtr = bitreaderJNI.ConstantStruct_getTypeForElements__SWIG_2(LLVMContext.getCPtr(Ctx), Ctx, SWIGTYPE_p_ArrayRefT_llvm__Constant_p_t.getCPtr(V), Packed);
    return (cPtr == 0) ? null : new SWIGTYPE_p_llvm__StructType(cPtr, false);
  }

  public static SWIGTYPE_p_llvm__StructType getTypeForElements(LLVMContext Ctx, SWIGTYPE_p_ArrayRefT_llvm__Constant_p_t V) {
    long cPtr = bitreaderJNI.ConstantStruct_getTypeForElements__SWIG_3(LLVMContext.getCPtr(Ctx), Ctx, SWIGTYPE_p_ArrayRefT_llvm__Constant_p_t.getCPtr(V));
    return (cPtr == 0) ? null : new SWIGTYPE_p_llvm__StructType(cPtr, false);
  }

  public SWIGTYPE_p_llvm__StructType getType() {
    long cPtr = bitreaderJNI.ConstantStruct_getType(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_llvm__StructType(cPtr, false);
  }

  public void destroyConstant() {
    bitreaderJNI.ConstantStruct_destroyConstant(swigCPtr, this);
  }

  public void replaceUsesOfWithOnConstant(Value From, Value To, SWIGTYPE_p_Use U) {
    bitreaderJNI.ConstantStruct_replaceUsesOfWithOnConstant(swigCPtr, this, Value.getCPtr(From), From, Value.getCPtr(To), To, SWIGTYPE_p_Use.getCPtr(U));
  }

  public static boolean classof(Value V) {
    return bitreaderJNI.ConstantStruct_classof(Value.getCPtr(V), V);
  }

}
