/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package na.okutane.cpp.llvm;

public class DebugInfoFinder {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected DebugInfoFinder(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DebugInfoFinder obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bitreaderJNI.delete_DebugInfoFinder(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void processModule(Module M) {
    bitreaderJNI.DebugInfoFinder_processModule(swigCPtr, this, Module.getCPtr(M), M);
  }

  public SWIGTYPE_p_SmallVectorT_llvm__MDNode_p_8_t__const_iterator compile_unit_begin() {
    return new SWIGTYPE_p_SmallVectorT_llvm__MDNode_p_8_t__const_iterator(bitreaderJNI.DebugInfoFinder_compile_unit_begin(swigCPtr, this), true);
  }

  public SWIGTYPE_p_SmallVectorT_llvm__MDNode_p_8_t__const_iterator compile_unit_end() {
    return new SWIGTYPE_p_SmallVectorT_llvm__MDNode_p_8_t__const_iterator(bitreaderJNI.DebugInfoFinder_compile_unit_end(swigCPtr, this), true);
  }

  public SWIGTYPE_p_SmallVectorT_llvm__MDNode_p_8_t__const_iterator subprogram_begin() {
    return new SWIGTYPE_p_SmallVectorT_llvm__MDNode_p_8_t__const_iterator(bitreaderJNI.DebugInfoFinder_subprogram_begin(swigCPtr, this), true);
  }

  public SWIGTYPE_p_SmallVectorT_llvm__MDNode_p_8_t__const_iterator subprogram_end() {
    return new SWIGTYPE_p_SmallVectorT_llvm__MDNode_p_8_t__const_iterator(bitreaderJNI.DebugInfoFinder_subprogram_end(swigCPtr, this), true);
  }

  public SWIGTYPE_p_SmallVectorT_llvm__MDNode_p_8_t__const_iterator global_variable_begin() {
    return new SWIGTYPE_p_SmallVectorT_llvm__MDNode_p_8_t__const_iterator(bitreaderJNI.DebugInfoFinder_global_variable_begin(swigCPtr, this), true);
  }

  public SWIGTYPE_p_SmallVectorT_llvm__MDNode_p_8_t__const_iterator global_variable_end() {
    return new SWIGTYPE_p_SmallVectorT_llvm__MDNode_p_8_t__const_iterator(bitreaderJNI.DebugInfoFinder_global_variable_end(swigCPtr, this), true);
  }

  public SWIGTYPE_p_SmallVectorT_llvm__MDNode_p_8_t__const_iterator type_begin() {
    return new SWIGTYPE_p_SmallVectorT_llvm__MDNode_p_8_t__const_iterator(bitreaderJNI.DebugInfoFinder_type_begin(swigCPtr, this), true);
  }

  public SWIGTYPE_p_SmallVectorT_llvm__MDNode_p_8_t__const_iterator type_end() {
    return new SWIGTYPE_p_SmallVectorT_llvm__MDNode_p_8_t__const_iterator(bitreaderJNI.DebugInfoFinder_type_end(swigCPtr, this), true);
  }

  public long compile_unit_count() {
    return bitreaderJNI.DebugInfoFinder_compile_unit_count(swigCPtr, this);
  }

  public long global_variable_count() {
    return bitreaderJNI.DebugInfoFinder_global_variable_count(swigCPtr, this);
  }

  public long subprogram_count() {
    return bitreaderJNI.DebugInfoFinder_subprogram_count(swigCPtr, this);
  }

  public long type_count() {
    return bitreaderJNI.DebugInfoFinder_type_count(swigCPtr, this);
  }

  public DebugInfoFinder() {
    this(bitreaderJNI.new_DebugInfoFinder(), true);
  }

}
