/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package na.okutane.cpp.llvm;

public class DIArray extends DIDescriptor {
  private long swigCPtr;

  protected DIArray(long cPtr, boolean cMemoryOwn) {
    super(bitreaderJNI.DIArray_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DIArray obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bitreaderJNI.delete_DIArray(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public DIArray(MDNode N) {
    this(bitreaderJNI.new_DIArray__SWIG_0(MDNode.getCPtr(N), N), true);
  }

  public DIArray() {
    this(bitreaderJNI.new_DIArray__SWIG_1(), true);
  }

  public long getNumElements() {
    return bitreaderJNI.DIArray_getNumElements(swigCPtr, this);
  }

  public DIDescriptor getElement(long Idx) {
    return new DIDescriptor(bitreaderJNI.DIArray_getElement(swigCPtr, this, Idx), true);
  }

}
