/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package na.okutane.cpp.llvm;

public class DIBasicType extends DIType {
  private long swigCPtr;

  protected DIBasicType(long cPtr, boolean cMemoryOwn) {
    super(bitreaderJNI.DIBasicType_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DIBasicType obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bitreaderJNI.delete_DIBasicType(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public DIBasicType(MDNode N) {
    this(bitreaderJNI.new_DIBasicType__SWIG_0(MDNode.getCPtr(N), N), true);
  }

  public DIBasicType() {
    this(bitreaderJNI.new_DIBasicType__SWIG_1(), true);
  }

  public long getEncoding() {
    return bitreaderJNI.DIBasicType_getEncoding(swigCPtr, this);
  }

  public boolean Verify() {
    return bitreaderJNI.DIBasicType_Verify(swigCPtr, this);
  }

}
