/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package na.okutane.cpp.llvm;

public class DICompositeType extends DIDerivedType {
  private long swigCPtr;

  protected DICompositeType(long cPtr, boolean cMemoryOwn) {
    super(bitreaderJNI.DICompositeType_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DICompositeType obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bitreaderJNI.delete_DICompositeType(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public DICompositeType(MDNode N) {
    this(bitreaderJNI.new_DICompositeType__SWIG_0(MDNode.getCPtr(N), N), true);
  }

  public DICompositeType() {
    this(bitreaderJNI.new_DICompositeType__SWIG_1(), true);
  }

  public DIArray getTypeArray() {
    return new DIArray(bitreaderJNI.DICompositeType_getTypeArray(swigCPtr, this), true);
  }

  public void setTypeArray(DIArray Elements, DIArray TParams) {
    bitreaderJNI.DICompositeType_setTypeArray__SWIG_0(swigCPtr, this, DIArray.getCPtr(Elements), Elements, DIArray.getCPtr(TParams), TParams);
  }

  public void setTypeArray(DIArray Elements) {
    bitreaderJNI.DICompositeType_setTypeArray__SWIG_1(swigCPtr, this, DIArray.getCPtr(Elements), Elements);
  }

  public long getRunTimeLang() {
    return bitreaderJNI.DICompositeType_getRunTimeLang(swigCPtr, this);
  }

  public DICompositeType getContainingType() {
    return new DICompositeType(bitreaderJNI.DICompositeType_getContainingType(swigCPtr, this), true);
  }

  public void setContainingType(DICompositeType ContainingType) {
    bitreaderJNI.DICompositeType_setContainingType(swigCPtr, this, DICompositeType.getCPtr(ContainingType), ContainingType);
  }

  public DIArray getTemplateParams() {
    return new DIArray(bitreaderJNI.DICompositeType_getTemplateParams(swigCPtr, this), true);
  }

  public boolean Verify() {
    return bitreaderJNI.DICompositeType_Verify(swigCPtr, this);
  }

}
