/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package na.okutane.cpp.llvm;

public class DIDerivedType extends DIType {
  private long swigCPtr;

  protected DIDerivedType(long cPtr, boolean cMemoryOwn) {
    super(bitreaderJNI.DIDerivedType_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DIDerivedType obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bitreaderJNI.delete_DIDerivedType(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public DIDerivedType(MDNode N) {
    this(bitreaderJNI.new_DIDerivedType__SWIG_1(MDNode.getCPtr(N), N), true);
  }

  public DIDerivedType() {
    this(bitreaderJNI.new_DIDerivedType__SWIG_2(), true);
  }

  public DIType getTypeDerivedFrom() {
    return new DIType(bitreaderJNI.DIDerivedType_getTypeDerivedFrom(swigCPtr, this), true);
  }

  public SWIGTYPE_p_uint64_t getOriginalTypeSize() {
    return new SWIGTYPE_p_uint64_t(bitreaderJNI.DIDerivedType_getOriginalTypeSize(swigCPtr, this), true);
  }

  public MDNode getObjCProperty() {
    long cPtr = bitreaderJNI.DIDerivedType_getObjCProperty(swigCPtr, this);
    return (cPtr == 0) ? null : new MDNode(cPtr, false);
  }

  public DIType getClassType() {
    return new DIType(bitreaderJNI.DIDerivedType_getClassType(swigCPtr, this), true);
  }

  public SWIGTYPE_p_llvm__Constant getConstant() {
    long cPtr = bitreaderJNI.DIDerivedType_getConstant(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_llvm__Constant(cPtr, false);
  }

  public boolean Verify() {
    return bitreaderJNI.DIDerivedType_Verify(swigCPtr, this);
  }

}
