/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package na.okutane.cpp.llvm;

public class DIFile extends DIScope {
  private long swigCPtr;

  protected DIFile(long cPtr, boolean cMemoryOwn) {
    super(bitreaderJNI.DIFile_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DIFile obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bitreaderJNI.delete_DIFile(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public DIFile(MDNode N) {
    this(bitreaderJNI.new_DIFile__SWIG_0(MDNode.getCPtr(N), N), true);
  }

  public DIFile() {
    this(bitreaderJNI.new_DIFile__SWIG_1(), true);
  }

  public MDNode getFileNode() {
    long cPtr = bitreaderJNI.DIFile_getFileNode(swigCPtr, this);
    return (cPtr == 0) ? null : new MDNode(cPtr, false);
  }

  public boolean Verify() {
    return bitreaderJNI.DIFile_Verify(swigCPtr, this);
  }

}
