/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package na.okutane.cpp.llvm;

public class DILexicalBlock extends DIScope {
  private long swigCPtr;

  protected DILexicalBlock(long cPtr, boolean cMemoryOwn) {
    super(bitreaderJNI.DILexicalBlock_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DILexicalBlock obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bitreaderJNI.delete_DILexicalBlock(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public DILexicalBlock(MDNode N) {
    this(bitreaderJNI.new_DILexicalBlock__SWIG_0(MDNode.getCPtr(N), N), true);
  }

  public DILexicalBlock() {
    this(bitreaderJNI.new_DILexicalBlock__SWIG_1(), true);
  }

  public DIScope getContext() {
    return new DIScope(bitreaderJNI.DILexicalBlock_getContext(swigCPtr, this), true);
  }

  public long getLineNumber() {
    return bitreaderJNI.DILexicalBlock_getLineNumber(swigCPtr, this);
  }

  public long getColumnNumber() {
    return bitreaderJNI.DILexicalBlock_getColumnNumber(swigCPtr, this);
  }

  public boolean Verify() {
    return bitreaderJNI.DILexicalBlock_Verify(swigCPtr, this);
  }

}
