/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package na.okutane.cpp.llvm;

public class DILocation extends DIDescriptor {
  private long swigCPtr;

  protected DILocation(long cPtr, boolean cMemoryOwn) {
    super(bitreaderJNI.DILocation_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DILocation obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bitreaderJNI.delete_DILocation(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public DILocation(MDNode N) {
    this(bitreaderJNI.new_DILocation(MDNode.getCPtr(N), N), true);
  }

  public long getLineNumber() {
    return bitreaderJNI.DILocation_getLineNumber(swigCPtr, this);
  }

  public long getColumnNumber() {
    return bitreaderJNI.DILocation_getColumnNumber(swigCPtr, this);
  }

  public DIScope getScope() {
    return new DIScope(bitreaderJNI.DILocation_getScope(swigCPtr, this), true);
  }

  public DILocation getOrigLocation() {
    return new DILocation(bitreaderJNI.DILocation_getOrigLocation(swigCPtr, this), true);
  }

  public StringRef getFilename() {
    return new StringRef(bitreaderJNI.DILocation_getFilename(swigCPtr, this), true);
  }

  public StringRef getDirectory() {
    return new StringRef(bitreaderJNI.DILocation_getDirectory(swigCPtr, this), true);
  }

  public boolean Verify() {
    return bitreaderJNI.DILocation_Verify(swigCPtr, this);
  }

}
