/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package na.okutane.cpp.llvm;

public class DINameSpace extends DIScope {
  private long swigCPtr;

  protected DINameSpace(long cPtr, boolean cMemoryOwn) {
    super(bitreaderJNI.DINameSpace_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DINameSpace obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bitreaderJNI.delete_DINameSpace(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public DINameSpace(MDNode N) {
    this(bitreaderJNI.new_DINameSpace__SWIG_0(MDNode.getCPtr(N), N), true);
  }

  public DINameSpace() {
    this(bitreaderJNI.new_DINameSpace__SWIG_1(), true);
  }

  public DIScope getContext() {
    return new DIScope(bitreaderJNI.DINameSpace_getContext(swigCPtr, this), true);
  }

  public StringRef getName() {
    return new StringRef(bitreaderJNI.DINameSpace_getName(swigCPtr, this), true);
  }

  public long getLineNumber() {
    return bitreaderJNI.DINameSpace_getLineNumber(swigCPtr, this);
  }

  public boolean Verify() {
    return bitreaderJNI.DINameSpace_Verify(swigCPtr, this);
  }

}
