/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package na.okutane.cpp.llvm;

public class DISubrange extends DIDescriptor {
  private long swigCPtr;

  protected DISubrange(long cPtr, boolean cMemoryOwn) {
    super(bitreaderJNI.DISubrange_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DISubrange obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bitreaderJNI.delete_DISubrange(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public DISubrange(MDNode N) {
    this(bitreaderJNI.new_DISubrange__SWIG_0(MDNode.getCPtr(N), N), true);
  }

  public DISubrange() {
    this(bitreaderJNI.new_DISubrange__SWIG_1(), true);
  }

  public SWIGTYPE_p_int64_t getLo() {
    return new SWIGTYPE_p_int64_t(bitreaderJNI.DISubrange_getLo(swigCPtr, this), true);
  }

  public SWIGTYPE_p_int64_t getCount() {
    return new SWIGTYPE_p_int64_t(bitreaderJNI.DISubrange_getCount(swigCPtr, this), true);
  }

  public boolean Verify() {
    return bitreaderJNI.DISubrange_Verify(swigCPtr, this);
  }

}
