/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package na.okutane.cpp.llvm;

public class DITemplateTypeParameter extends DIDescriptor {
  private long swigCPtr;

  protected DITemplateTypeParameter(long cPtr, boolean cMemoryOwn) {
    super(bitreaderJNI.DITemplateTypeParameter_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DITemplateTypeParameter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bitreaderJNI.delete_DITemplateTypeParameter(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public DITemplateTypeParameter(MDNode N) {
    this(bitreaderJNI.new_DITemplateTypeParameter__SWIG_0(MDNode.getCPtr(N), N), true);
  }

  public DITemplateTypeParameter() {
    this(bitreaderJNI.new_DITemplateTypeParameter__SWIG_1(), true);
  }

  public DIScope getContext() {
    return new DIScope(bitreaderJNI.DITemplateTypeParameter_getContext(swigCPtr, this), true);
  }

  public StringRef getName() {
    return new StringRef(bitreaderJNI.DITemplateTypeParameter_getName(swigCPtr, this), true);
  }

  public DIType getType() {
    return new DIType(bitreaderJNI.DITemplateTypeParameter_getType(swigCPtr, this), true);
  }

  public StringRef getFilename() {
    return new StringRef(bitreaderJNI.DITemplateTypeParameter_getFilename(swigCPtr, this), true);
  }

  public StringRef getDirectory() {
    return new StringRef(bitreaderJNI.DITemplateTypeParameter_getDirectory(swigCPtr, this), true);
  }

  public long getLineNumber() {
    return bitreaderJNI.DITemplateTypeParameter_getLineNumber(swigCPtr, this);
  }

  public long getColumnNumber() {
    return bitreaderJNI.DITemplateTypeParameter_getColumnNumber(swigCPtr, this);
  }

  public boolean Verify() {
    return bitreaderJNI.DITemplateTypeParameter_Verify(swigCPtr, this);
  }

}
