/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package na.okutane.cpp.llvm;

public class DITemplateValueParameter extends DIDescriptor {
  private long swigCPtr;

  protected DITemplateValueParameter(long cPtr, boolean cMemoryOwn) {
    super(bitreaderJNI.DITemplateValueParameter_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DITemplateValueParameter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bitreaderJNI.delete_DITemplateValueParameter(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public DITemplateValueParameter(MDNode N) {
    this(bitreaderJNI.new_DITemplateValueParameter__SWIG_0(MDNode.getCPtr(N), N), true);
  }

  public DITemplateValueParameter() {
    this(bitreaderJNI.new_DITemplateValueParameter__SWIG_1(), true);
  }

  public DIScope getContext() {
    return new DIScope(bitreaderJNI.DITemplateValueParameter_getContext(swigCPtr, this), true);
  }

  public StringRef getName() {
    return new StringRef(bitreaderJNI.DITemplateValueParameter_getName(swigCPtr, this), true);
  }

  public DIType getType() {
    return new DIType(bitreaderJNI.DITemplateValueParameter_getType(swigCPtr, this), true);
  }

  public SWIGTYPE_p_uint64_t getValue() {
    return new SWIGTYPE_p_uint64_t(bitreaderJNI.DITemplateValueParameter_getValue(swigCPtr, this), true);
  }

  public StringRef getFilename() {
    return new StringRef(bitreaderJNI.DITemplateValueParameter_getFilename(swigCPtr, this), true);
  }

  public StringRef getDirectory() {
    return new StringRef(bitreaderJNI.DITemplateValueParameter_getDirectory(swigCPtr, this), true);
  }

  public long getLineNumber() {
    return bitreaderJNI.DITemplateValueParameter_getLineNumber(swigCPtr, this);
  }

  public long getColumnNumber() {
    return bitreaderJNI.DITemplateValueParameter_getColumnNumber(swigCPtr, this);
  }

  public boolean Verify() {
    return bitreaderJNI.DITemplateValueParameter_Verify(swigCPtr, this);
  }

}
