/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package na.okutane.cpp.llvm;

public class DIVariable extends DIDescriptor {
  private long swigCPtr;

  protected DIVariable(long cPtr, boolean cMemoryOwn) {
    super(bitreaderJNI.DIVariable_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DIVariable obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bitreaderJNI.delete_DIVariable(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public DIVariable(MDNode N) {
    this(bitreaderJNI.new_DIVariable__SWIG_0(MDNode.getCPtr(N), N), true);
  }

  public DIVariable() {
    this(bitreaderJNI.new_DIVariable__SWIG_1(), true);
  }

  public DIScope getContext() {
    return new DIScope(bitreaderJNI.DIVariable_getContext(swigCPtr, this), true);
  }

  public StringRef getName() {
    return new StringRef(bitreaderJNI.DIVariable_getName(swigCPtr, this), true);
  }

  public DIFile getFile() {
    return new DIFile(bitreaderJNI.DIVariable_getFile(swigCPtr, this), true);
  }

  public long getLineNumber() {
    return bitreaderJNI.DIVariable_getLineNumber(swigCPtr, this);
  }

  public long getArgNumber() {
    return bitreaderJNI.DIVariable_getArgNumber(swigCPtr, this);
  }

  public DIType getType() {
    return new DIType(bitreaderJNI.DIVariable_getType(swigCPtr, this), true);
  }

  public boolean isArtificial() {
    return bitreaderJNI.DIVariable_isArtificial(swigCPtr, this);
  }

  public boolean isObjectPointer() {
    return bitreaderJNI.DIVariable_isObjectPointer(swigCPtr, this);
  }

  public MDNode getInlinedAt() {
    long cPtr = bitreaderJNI.DIVariable_getInlinedAt(swigCPtr, this);
    return (cPtr == 0) ? null : new MDNode(cPtr, false);
  }

  public boolean Verify() {
    return bitreaderJNI.DIVariable_Verify(swigCPtr, this);
  }

  public boolean hasComplexAddress() {
    return bitreaderJNI.DIVariable_hasComplexAddress(swigCPtr, this);
  }

  public long getNumAddrElements() {
    return bitreaderJNI.DIVariable_getNumAddrElements(swigCPtr, this);
  }

  public SWIGTYPE_p_uint64_t getAddrElement(long Idx) {
    return new SWIGTYPE_p_uint64_t(bitreaderJNI.DIVariable_getAddrElement(swigCPtr, this, Idx), true);
  }

  public boolean isBlockByrefVariable() {
    return bitreaderJNI.DIVariable_isBlockByrefVariable(swigCPtr, this);
  }

  public boolean isInlinedFnArgument(Function CurFn) {
    return bitreaderJNI.DIVariable_isInlinedFnArgument(swigCPtr, this, Function.getCPtr(CurFn), CurFn);
  }

  public void printExtendedName(SWIGTYPE_p_llvm__raw_ostream OS) {
    bitreaderJNI.DIVariable_printExtendedName(swigCPtr, this, SWIGTYPE_p_llvm__raw_ostream.getCPtr(OS));
  }

}
