/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package na.okutane.cpp.llvm;

public class ExtractElementInst extends Instruction {
  private long swigCPtr;

  protected ExtractElementInst(long cPtr, boolean cMemoryOwn) {
    super(bitreaderJNI.ExtractElementInst_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ExtractElementInst obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bitreaderJNI.delete_ExtractElementInst(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static ExtractElementInst Create(Value Vec, Value Idx, SWIGTYPE_p_llvm__Twine NameStr, Instruction InsertBefore) {
    long cPtr = bitreaderJNI.ExtractElementInst_Create__SWIG_0(Value.getCPtr(Vec), Vec, Value.getCPtr(Idx), Idx, SWIGTYPE_p_llvm__Twine.getCPtr(NameStr), Instruction.getCPtr(InsertBefore), InsertBefore);
    return (cPtr == 0) ? null : new ExtractElementInst(cPtr, false);
  }

  public static ExtractElementInst Create(Value Vec, Value Idx, SWIGTYPE_p_llvm__Twine NameStr) {
    long cPtr = bitreaderJNI.ExtractElementInst_Create__SWIG_1(Value.getCPtr(Vec), Vec, Value.getCPtr(Idx), Idx, SWIGTYPE_p_llvm__Twine.getCPtr(NameStr));
    return (cPtr == 0) ? null : new ExtractElementInst(cPtr, false);
  }

  public static ExtractElementInst Create(Value Vec, Value Idx) {
    long cPtr = bitreaderJNI.ExtractElementInst_Create__SWIG_2(Value.getCPtr(Vec), Vec, Value.getCPtr(Idx), Idx);
    return (cPtr == 0) ? null : new ExtractElementInst(cPtr, false);
  }

  public static ExtractElementInst Create(Value Vec, Value Idx, SWIGTYPE_p_llvm__Twine NameStr, BasicBlock InsertAtEnd) {
    long cPtr = bitreaderJNI.ExtractElementInst_Create__SWIG_3(Value.getCPtr(Vec), Vec, Value.getCPtr(Idx), Idx, SWIGTYPE_p_llvm__Twine.getCPtr(NameStr), BasicBlock.getCPtr(InsertAtEnd), InsertAtEnd);
    return (cPtr == 0) ? null : new ExtractElementInst(cPtr, false);
  }

  public static boolean isValidOperands(Value Vec, Value Idx) {
    return bitreaderJNI.ExtractElementInst_isValidOperands(Value.getCPtr(Vec), Vec, Value.getCPtr(Idx), Idx);
  }

  public Value getVectorOperand() {
    long cPtr = bitreaderJNI.ExtractElementInst_getVectorOperand__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new Value(cPtr, false);
  }

  public Value getIndexOperand() {
    long cPtr = bitreaderJNI.ExtractElementInst_getIndexOperand__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new Value(cPtr, false);
  }

  public SWIGTYPE_p_llvm__VectorType getVectorOperandType() {
    long cPtr = bitreaderJNI.ExtractElementInst_getVectorOperandType(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_llvm__VectorType(cPtr, false);
  }

  public static boolean classof(Instruction I) {
    return bitreaderJNI.ExtractElementInst_classof__SWIG_0(Instruction.getCPtr(I), I);
  }

  public static boolean classof(Value V) {
    return bitreaderJNI.ExtractElementInst_classof__SWIG_1(Value.getCPtr(V), V);
  }

}
