/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package na.okutane.cpp.llvm;

public class FenceInst extends Instruction {
  private long swigCPtr;

  protected FenceInst(long cPtr, boolean cMemoryOwn) {
    super(bitreaderJNI.FenceInst_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FenceInst obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bitreaderJNI.delete_FenceInst(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public AtomicOrdering getOrdering() {
    return AtomicOrdering.swigToEnum(bitreaderJNI.FenceInst_getOrdering(swigCPtr, this));
  }

  public void setOrdering(AtomicOrdering Ordering) {
    bitreaderJNI.FenceInst_setOrdering(swigCPtr, this, Ordering.swigValue());
  }

  public SynchronizationScope getSynchScope() {
    return SynchronizationScope.swigToEnum(bitreaderJNI.FenceInst_getSynchScope(swigCPtr, this));
  }

  public void setSynchScope(SynchronizationScope xthread) {
    bitreaderJNI.FenceInst_setSynchScope(swigCPtr, this, xthread.swigValue());
  }

  public static boolean classof(Instruction I) {
    return bitreaderJNI.FenceInst_classof__SWIG_0(Instruction.getCPtr(I), I);
  }

  public static boolean classof(Value V) {
    return bitreaderJNI.FenceInst_classof__SWIG_1(Value.getCPtr(V), V);
  }

}
