/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package na.okutane.cpp.llvm;

public class Function extends GlobalValue {
  private long swigCPtr;

  protected Function(long cPtr, boolean cMemoryOwn) {
    super(bitreaderJNI.Function_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Function obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bitreaderJNI.delete_Function(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static Function Create(SWIGTYPE_p_llvm__FunctionType Ty, GlobalValue.LinkageTypes Linkage, SWIGTYPE_p_llvm__Twine N, Module M) {
    long cPtr = bitreaderJNI.Function_Create__SWIG_0(SWIGTYPE_p_llvm__FunctionType.getCPtr(Ty), Linkage.swigValue(), SWIGTYPE_p_llvm__Twine.getCPtr(N), Module.getCPtr(M), M);
    return (cPtr == 0) ? null : new Function(cPtr, false);
  }

  public static Function Create(SWIGTYPE_p_llvm__FunctionType Ty, GlobalValue.LinkageTypes Linkage, SWIGTYPE_p_llvm__Twine N) {
    long cPtr = bitreaderJNI.Function_Create__SWIG_1(SWIGTYPE_p_llvm__FunctionType.getCPtr(Ty), Linkage.swigValue(), SWIGTYPE_p_llvm__Twine.getCPtr(N));
    return (cPtr == 0) ? null : new Function(cPtr, false);
  }

  public static Function Create(SWIGTYPE_p_llvm__FunctionType Ty, GlobalValue.LinkageTypes Linkage) {
    long cPtr = bitreaderJNI.Function_Create__SWIG_2(SWIGTYPE_p_llvm__FunctionType.getCPtr(Ty), Linkage.swigValue());
    return (cPtr == 0) ? null : new Function(cPtr, false);
  }

  public Type getReturnType() {
    long cPtr = bitreaderJNI.Function_getReturnType(swigCPtr, this);
    return (cPtr == 0) ? null : new Type(cPtr, false);
  }

  public SWIGTYPE_p_llvm__FunctionType getFunctionType() {
    long cPtr = bitreaderJNI.Function_getFunctionType(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_llvm__FunctionType(cPtr, false);
  }

  public LLVMContext getContext() {
    return new LLVMContext(bitreaderJNI.Function_getContext(swigCPtr, this), false);
  }

  public boolean isVarArg() {
    return bitreaderJNI.Function_isVarArg(swigCPtr, this);
  }

  public long getIntrinsicID() {
    return bitreaderJNI.Function_getIntrinsicID(swigCPtr, this);
  }

  public boolean isIntrinsic() {
    return bitreaderJNI.Function_isIntrinsic(swigCPtr, this);
  }

  public SWIGTYPE_p_CallingConv__ID getCallingConv() {
    return new SWIGTYPE_p_CallingConv__ID(bitreaderJNI.Function_getCallingConv(swigCPtr, this), true);
  }

  public void setCallingConv(SWIGTYPE_p_CallingConv__ID CC) {
    bitreaderJNI.Function_setCallingConv(swigCPtr, this, SWIGTYPE_p_CallingConv__ID.getCPtr(CC));
  }

  public SWIGTYPE_p_AttributeSet getAttributes() {
    return new SWIGTYPE_p_AttributeSet(bitreaderJNI.Function_getAttributes(swigCPtr, this), true);
  }

  public void setAttributes(SWIGTYPE_p_AttributeSet attrs) {
    bitreaderJNI.Function_setAttributes(swigCPtr, this, SWIGTYPE_p_AttributeSet.getCPtr(attrs));
  }

  public void addFnAttr(SWIGTYPE_p_Attribute__AttrKind N) {
    bitreaderJNI.Function_addFnAttr__SWIG_0(swigCPtr, this, SWIGTYPE_p_Attribute__AttrKind.getCPtr(N));
  }

  public void addFnAttr(StringRef Kind) {
    bitreaderJNI.Function_addFnAttr__SWIG_1(swigCPtr, this, StringRef.getCPtr(Kind), Kind);
  }

  public boolean hasFnAttribute(SWIGTYPE_p_Attribute__AttrKind Kind) {
    return bitreaderJNI.Function_hasFnAttribute__SWIG_0(swigCPtr, this, SWIGTYPE_p_Attribute__AttrKind.getCPtr(Kind));
  }

  public boolean hasFnAttribute(StringRef Kind) {
    return bitreaderJNI.Function_hasFnAttribute__SWIG_1(swigCPtr, this, StringRef.getCPtr(Kind), Kind);
  }

  public boolean hasGC() {
    return bitreaderJNI.Function_hasGC(swigCPtr, this);
  }

  public String getGC() {
    return bitreaderJNI.Function_getGC(swigCPtr, this);
  }

  public void setGC(String Str) {
    bitreaderJNI.Function_setGC(swigCPtr, this, Str);
  }

  public void clearGC() {
    bitreaderJNI.Function_clearGC(swigCPtr, this);
  }

  public void addAttribute(long i, SWIGTYPE_p_Attribute__AttrKind attr) {
    bitreaderJNI.Function_addAttribute(swigCPtr, this, i, SWIGTYPE_p_Attribute__AttrKind.getCPtr(attr));
  }

  public void addAttributes(long i, SWIGTYPE_p_AttributeSet attrs) {
    bitreaderJNI.Function_addAttributes(swigCPtr, this, i, SWIGTYPE_p_AttributeSet.getCPtr(attrs));
  }

  public void removeAttributes(long i, SWIGTYPE_p_AttributeSet attr) {
    bitreaderJNI.Function_removeAttributes(swigCPtr, this, i, SWIGTYPE_p_AttributeSet.getCPtr(attr));
  }

  public long getParamAlignment(long i) {
    return bitreaderJNI.Function_getParamAlignment(swigCPtr, this, i);
  }

  public boolean doesNotAccessMemory() {
    return bitreaderJNI.Function_doesNotAccessMemory(swigCPtr, this);
  }

  public void setDoesNotAccessMemory() {
    bitreaderJNI.Function_setDoesNotAccessMemory(swigCPtr, this);
  }

  public boolean onlyReadsMemory() {
    return bitreaderJNI.Function_onlyReadsMemory(swigCPtr, this);
  }

  public void setOnlyReadsMemory() {
    bitreaderJNI.Function_setOnlyReadsMemory(swigCPtr, this);
  }

  public boolean doesNotReturn() {
    return bitreaderJNI.Function_doesNotReturn(swigCPtr, this);
  }

  public void setDoesNotReturn() {
    bitreaderJNI.Function_setDoesNotReturn(swigCPtr, this);
  }

  public boolean doesNotThrow() {
    return bitreaderJNI.Function_doesNotThrow(swigCPtr, this);
  }

  public void setDoesNotThrow() {
    bitreaderJNI.Function_setDoesNotThrow(swigCPtr, this);
  }

  public boolean cannotDuplicate() {
    return bitreaderJNI.Function_cannotDuplicate(swigCPtr, this);
  }

  public void setCannotDuplicate() {
    bitreaderJNI.Function_setCannotDuplicate(swigCPtr, this);
  }

  public boolean hasUWTable() {
    return bitreaderJNI.Function_hasUWTable(swigCPtr, this);
  }

  public void setHasUWTable() {
    bitreaderJNI.Function_setHasUWTable(swigCPtr, this);
  }

  public boolean needsUnwindTableEntry() {
    return bitreaderJNI.Function_needsUnwindTableEntry(swigCPtr, this);
  }

  public boolean hasStructRetAttr() {
    return bitreaderJNI.Function_hasStructRetAttr(swigCPtr, this);
  }

  public boolean doesNotAlias(long n) {
    return bitreaderJNI.Function_doesNotAlias(swigCPtr, this, n);
  }

  public void setDoesNotAlias(long n) {
    bitreaderJNI.Function_setDoesNotAlias(swigCPtr, this, n);
  }

  public boolean doesNotCapture(long n) {
    return bitreaderJNI.Function_doesNotCapture(swigCPtr, this, n);
  }

  public void setDoesNotCapture(long n) {
    bitreaderJNI.Function_setDoesNotCapture(swigCPtr, this, n);
  }

  public void copyAttributesFrom(GlobalValue Src) {
    bitreaderJNI.Function_copyAttributesFrom(swigCPtr, this, GlobalValue.getCPtr(Src), Src);
  }

  public void deleteBody() {
    bitreaderJNI.Function_deleteBody(swigCPtr, this);
  }

  public void removeFromParent() {
    bitreaderJNI.Function_removeFromParent(swigCPtr, this);
  }

  public void eraseFromParent() {
    bitreaderJNI.Function_eraseFromParent(swigCPtr, this);
  }

  public SWIGTYPE_p_llvm__iplistT_llvm__Argument_t getArgumentList() {
    return new SWIGTYPE_p_llvm__iplistT_llvm__Argument_t(bitreaderJNI.Function_getArgumentList__SWIG_0(swigCPtr, this), false);
  }

  public static SWIGTYPE_m_Function__llvm__iplistT_llvm__Argument_t getSublistAccess(SWIGTYPE_p_llvm__Argument arg0) {
    String cMemberPtr = bitreaderJNI.Function_getSublistAccess__SWIG_0(SWIGTYPE_p_llvm__Argument.getCPtr(arg0));
    return (cMemberPtr == null) ? null : new SWIGTYPE_m_Function__llvm__iplistT_llvm__Argument_t(cMemberPtr, false);
  }

  public SWIGTYPE_p_llvm__iplistT_llvm__BasicBlock_t getBasicBlockList() {
    return new SWIGTYPE_p_llvm__iplistT_llvm__BasicBlock_t(bitreaderJNI.Function_getBasicBlockList__SWIG_0(swigCPtr, this), false);
  }

  public static SWIGTYPE_m_Function__llvm__iplistT_llvm__BasicBlock_t getSublistAccess(BasicBlock arg0) {
    String cMemberPtr = bitreaderJNI.Function_getSublistAccess__SWIG_1(BasicBlock.getCPtr(arg0), arg0);
    return (cMemberPtr == null) ? null : new SWIGTYPE_m_Function__llvm__iplistT_llvm__BasicBlock_t(cMemberPtr, false);
  }

  public BasicBlock getEntryBlock() {
    return new BasicBlock(bitreaderJNI.Function_getEntryBlock__SWIG_0(swigCPtr, this), false);
  }

  public SWIGTYPE_p_llvm__ValueSymbolTable getValueSymbolTable() {
    return new SWIGTYPE_p_llvm__ValueSymbolTable(bitreaderJNI.Function_getValueSymbolTable__SWIG_0(swigCPtr, this), false);
  }

  public SWIGTYPE_p_llvm__iplistT_llvm__BasicBlock_t__iterator begin() {
    return new SWIGTYPE_p_llvm__iplistT_llvm__BasicBlock_t__iterator(bitreaderJNI.Function_begin__SWIG_0(swigCPtr, this), true);
  }

  public SWIGTYPE_p_llvm__iplistT_llvm__BasicBlock_t__iterator end() {
    return new SWIGTYPE_p_llvm__iplistT_llvm__BasicBlock_t__iterator(bitreaderJNI.Function_end__SWIG_0(swigCPtr, this), true);
  }

  public long size() {
    return bitreaderJNI.Function_size(swigCPtr, this);
  }

  public boolean empty() {
    return bitreaderJNI.Function_empty(swigCPtr, this);
  }

  public BasicBlock front() {
    return new BasicBlock(bitreaderJNI.Function_front__SWIG_0(swigCPtr, this), false);
  }

  public BasicBlock back() {
    return new BasicBlock(bitreaderJNI.Function_back__SWIG_0(swigCPtr, this), false);
  }

  public SWIGTYPE_p_llvm__iplistT_llvm__Argument_t__iterator arg_begin() {
    return new SWIGTYPE_p_llvm__iplistT_llvm__Argument_t__iterator(bitreaderJNI.Function_arg_begin__SWIG_0(swigCPtr, this), true);
  }

  public SWIGTYPE_p_llvm__iplistT_llvm__Argument_t__iterator arg_end() {
    return new SWIGTYPE_p_llvm__iplistT_llvm__Argument_t__iterator(bitreaderJNI.Function_arg_end__SWIG_0(swigCPtr, this), true);
  }

  public long arg_size() {
    return bitreaderJNI.Function_arg_size(swigCPtr, this);
  }

  public boolean arg_empty() {
    return bitreaderJNI.Function_arg_empty(swigCPtr, this);
  }

  public void viewCFG() {
    bitreaderJNI.Function_viewCFG(swigCPtr, this);
  }

  public void viewCFGOnly() {
    bitreaderJNI.Function_viewCFGOnly(swigCPtr, this);
  }

  public static boolean classof(Value V) {
    return bitreaderJNI.Function_classof(Value.getCPtr(V), V);
  }

  public void dropAllReferences() {
    bitreaderJNI.Function_dropAllReferences(swigCPtr, this);
  }

  public boolean hasAddressTaken(SWIGTYPE_p_p_User arg0) {
    return bitreaderJNI.Function_hasAddressTaken__SWIG_0(swigCPtr, this, SWIGTYPE_p_p_User.getCPtr(arg0));
  }

  public boolean hasAddressTaken() {
    return bitreaderJNI.Function_hasAddressTaken__SWIG_1(swigCPtr, this);
  }

  public boolean isDefTriviallyDead() {
    return bitreaderJNI.Function_isDefTriviallyDead(swigCPtr, this);
  }

  public boolean callsFunctionThatReturnsTwice() {
    return bitreaderJNI.Function_callsFunctionThatReturnsTwice(swigCPtr, this);
  }

}
