/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package na.okutane.cpp.llvm;

public class ICmpInst {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ICmpInst(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ICmpInst obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bitreaderJNI.delete_ICmpInst(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ICmpInst(Instruction InsertBefore, SWIGTYPE_p_Predicate pred, Value LHS, Value RHS, SWIGTYPE_p_llvm__Twine NameStr) {
    this(bitreaderJNI.new_ICmpInst__SWIG_0(Instruction.getCPtr(InsertBefore), InsertBefore, SWIGTYPE_p_Predicate.getCPtr(pred), Value.getCPtr(LHS), LHS, Value.getCPtr(RHS), RHS, SWIGTYPE_p_llvm__Twine.getCPtr(NameStr)), true);
  }

  public ICmpInst(Instruction InsertBefore, SWIGTYPE_p_Predicate pred, Value LHS, Value RHS) {
    this(bitreaderJNI.new_ICmpInst__SWIG_1(Instruction.getCPtr(InsertBefore), InsertBefore, SWIGTYPE_p_Predicate.getCPtr(pred), Value.getCPtr(LHS), LHS, Value.getCPtr(RHS), RHS), true);
  }

  public ICmpInst(BasicBlock InsertAtEnd, SWIGTYPE_p_Predicate pred, Value LHS, Value RHS, SWIGTYPE_p_llvm__Twine NameStr) {
    this(bitreaderJNI.new_ICmpInst__SWIG_2(BasicBlock.getCPtr(InsertAtEnd), InsertAtEnd, SWIGTYPE_p_Predicate.getCPtr(pred), Value.getCPtr(LHS), LHS, Value.getCPtr(RHS), RHS, SWIGTYPE_p_llvm__Twine.getCPtr(NameStr)), true);
  }

  public ICmpInst(BasicBlock InsertAtEnd, SWIGTYPE_p_Predicate pred, Value LHS, Value RHS) {
    this(bitreaderJNI.new_ICmpInst__SWIG_3(BasicBlock.getCPtr(InsertAtEnd), InsertAtEnd, SWIGTYPE_p_Predicate.getCPtr(pred), Value.getCPtr(LHS), LHS, Value.getCPtr(RHS), RHS), true);
  }

  public ICmpInst(SWIGTYPE_p_Predicate pred, Value LHS, Value RHS, SWIGTYPE_p_llvm__Twine NameStr) {
    this(bitreaderJNI.new_ICmpInst__SWIG_4(SWIGTYPE_p_Predicate.getCPtr(pred), Value.getCPtr(LHS), LHS, Value.getCPtr(RHS), RHS, SWIGTYPE_p_llvm__Twine.getCPtr(NameStr)), true);
  }

  public ICmpInst(SWIGTYPE_p_Predicate pred, Value LHS, Value RHS) {
    this(bitreaderJNI.new_ICmpInst__SWIG_5(SWIGTYPE_p_Predicate.getCPtr(pred), Value.getCPtr(LHS), LHS, Value.getCPtr(RHS), RHS), true);
  }

  public SWIGTYPE_p_Predicate getSignedPredicate() {
    return new SWIGTYPE_p_Predicate(bitreaderJNI.ICmpInst_getSignedPredicate__SWIG_0(swigCPtr, this), true);
  }

  public static SWIGTYPE_p_Predicate getSignedPredicate(SWIGTYPE_p_Predicate pred) {
    return new SWIGTYPE_p_Predicate(bitreaderJNI.ICmpInst_getSignedPredicate__SWIG_1(SWIGTYPE_p_Predicate.getCPtr(pred)), true);
  }

  public SWIGTYPE_p_Predicate getUnsignedPredicate() {
    return new SWIGTYPE_p_Predicate(bitreaderJNI.ICmpInst_getUnsignedPredicate__SWIG_0(swigCPtr, this), true);
  }

  public static SWIGTYPE_p_Predicate getUnsignedPredicate(SWIGTYPE_p_Predicate pred) {
    return new SWIGTYPE_p_Predicate(bitreaderJNI.ICmpInst_getUnsignedPredicate__SWIG_1(SWIGTYPE_p_Predicate.getCPtr(pred)), true);
  }

  public static boolean isEquality(SWIGTYPE_p_Predicate P) {
    return bitreaderJNI.ICmpInst_isEquality__SWIG_0(SWIGTYPE_p_Predicate.getCPtr(P));
  }

  public boolean isEquality() {
    return bitreaderJNI.ICmpInst_isEquality__SWIG_1(swigCPtr, this);
  }

  public boolean isCommutative() {
    return bitreaderJNI.ICmpInst_isCommutative(swigCPtr, this);
  }

  public boolean isRelational() {
    return bitreaderJNI.ICmpInst_isRelational__SWIG_0(swigCPtr, this);
  }

  public static boolean isRelational(SWIGTYPE_p_Predicate P) {
    return bitreaderJNI.ICmpInst_isRelational__SWIG_1(SWIGTYPE_p_Predicate.getCPtr(P));
  }

  public static SWIGTYPE_p_llvm__ConstantRange makeConstantRange(SWIGTYPE_p_Predicate pred, APInt C) {
    return new SWIGTYPE_p_llvm__ConstantRange(bitreaderJNI.ICmpInst_makeConstantRange(SWIGTYPE_p_Predicate.getCPtr(pred), APInt.getCPtr(C), C), true);
  }

  public void swapOperands() {
    bitreaderJNI.ICmpInst_swapOperands(swigCPtr, this);
  }

  public static boolean classof(Instruction I) {
    return bitreaderJNI.ICmpInst_classof__SWIG_0(Instruction.getCPtr(I), I);
  }

  public static boolean classof(Value V) {
    return bitreaderJNI.ICmpInst_classof__SWIG_1(Value.getCPtr(V), V);
  }

}
