/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package na.okutane.cpp.llvm;

public class IndirectBrInst {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IndirectBrInst(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IndirectBrInst obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bitreaderJNI.delete_IndirectBrInst(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static IndirectBrInst Create(Value Address, long NumDests, Instruction InsertBefore) {
    long cPtr = bitreaderJNI.IndirectBrInst_Create__SWIG_0(Value.getCPtr(Address), Address, NumDests, Instruction.getCPtr(InsertBefore), InsertBefore);
    return (cPtr == 0) ? null : new IndirectBrInst(cPtr, false);
  }

  public static IndirectBrInst Create(Value Address, long NumDests) {
    long cPtr = bitreaderJNI.IndirectBrInst_Create__SWIG_1(Value.getCPtr(Address), Address, NumDests);
    return (cPtr == 0) ? null : new IndirectBrInst(cPtr, false);
  }

  public static IndirectBrInst Create(Value Address, long NumDests, BasicBlock InsertAtEnd) {
    long cPtr = bitreaderJNI.IndirectBrInst_Create__SWIG_2(Value.getCPtr(Address), Address, NumDests, BasicBlock.getCPtr(InsertAtEnd), InsertAtEnd);
    return (cPtr == 0) ? null : new IndirectBrInst(cPtr, false);
  }

  public Value getAddress() {
    long cPtr = bitreaderJNI.IndirectBrInst_getAddress__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new Value(cPtr, false);
  }

  public void setAddress(Value V) {
    bitreaderJNI.IndirectBrInst_setAddress(swigCPtr, this, Value.getCPtr(V), V);
  }

  public long getNumDestinations() {
    return bitreaderJNI.IndirectBrInst_getNumDestinations(swigCPtr, this);
  }

  public BasicBlock getDestination(long i) {
    long cPtr = bitreaderJNI.IndirectBrInst_getDestination__SWIG_0(swigCPtr, this, i);
    return (cPtr == 0) ? null : new BasicBlock(cPtr, false);
  }

  public void addDestination(BasicBlock Dest) {
    bitreaderJNI.IndirectBrInst_addDestination(swigCPtr, this, BasicBlock.getCPtr(Dest), Dest);
  }

  public void removeDestination(long i) {
    bitreaderJNI.IndirectBrInst_removeDestination(swigCPtr, this, i);
  }

  public long getNumSuccessors() {
    return bitreaderJNI.IndirectBrInst_getNumSuccessors(swigCPtr, this);
  }

  public BasicBlock getSuccessor(long i) {
    long cPtr = bitreaderJNI.IndirectBrInst_getSuccessor(swigCPtr, this, i);
    return (cPtr == 0) ? null : new BasicBlock(cPtr, false);
  }

  public void setSuccessor(long i, BasicBlock NewSucc) {
    bitreaderJNI.IndirectBrInst_setSuccessor(swigCPtr, this, i, BasicBlock.getCPtr(NewSucc), NewSucc);
  }

  public static boolean classof(Instruction I) {
    return bitreaderJNI.IndirectBrInst_classof__SWIG_0(Instruction.getCPtr(I), I);
  }

  public static boolean classof(Value V) {
    return bitreaderJNI.IndirectBrInst_classof__SWIG_1(Value.getCPtr(V), V);
  }

}
