/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package na.okutane.cpp.llvm;

public class IntToPtrInst {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected IntToPtrInst(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IntToPtrInst obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bitreaderJNI.delete_IntToPtrInst(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public IntToPtrInst(Value S, Type Ty, SWIGTYPE_p_llvm__Twine NameStr, Instruction InsertBefore) {
    this(bitreaderJNI.new_IntToPtrInst__SWIG_0(Value.getCPtr(S), S, Type.getCPtr(Ty), Ty, SWIGTYPE_p_llvm__Twine.getCPtr(NameStr), Instruction.getCPtr(InsertBefore), InsertBefore), true);
  }

  public IntToPtrInst(Value S, Type Ty, SWIGTYPE_p_llvm__Twine NameStr) {
    this(bitreaderJNI.new_IntToPtrInst__SWIG_1(Value.getCPtr(S), S, Type.getCPtr(Ty), Ty, SWIGTYPE_p_llvm__Twine.getCPtr(NameStr)), true);
  }

  public IntToPtrInst(Value S, Type Ty) {
    this(bitreaderJNI.new_IntToPtrInst__SWIG_2(Value.getCPtr(S), S, Type.getCPtr(Ty), Ty), true);
  }

  public IntToPtrInst(Value S, Type Ty, SWIGTYPE_p_llvm__Twine NameStr, BasicBlock InsertAtEnd) {
    this(bitreaderJNI.new_IntToPtrInst__SWIG_3(Value.getCPtr(S), S, Type.getCPtr(Ty), Ty, SWIGTYPE_p_llvm__Twine.getCPtr(NameStr), BasicBlock.getCPtr(InsertAtEnd), InsertAtEnd), true);
  }

  public IntToPtrInst clone_impl() {
    long cPtr = bitreaderJNI.IntToPtrInst_clone_impl(swigCPtr, this);
    return (cPtr == 0) ? null : new IntToPtrInst(cPtr, false);
  }

  public long getAddressSpace() {
    return bitreaderJNI.IntToPtrInst_getAddressSpace(swigCPtr, this);
  }

  public static boolean classof(Instruction I) {
    return bitreaderJNI.IntToPtrInst_classof__SWIG_0(Instruction.getCPtr(I), I);
  }

  public static boolean classof(Value V) {
    return bitreaderJNI.IntToPtrInst_classof__SWIG_1(Value.getCPtr(V), V);
  }

}
