/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package na.okutane.cpp.llvm;

public class LoadInst {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected LoadInst(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LoadInst obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bitreaderJNI.delete_LoadInst(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public LoadInst(Value Ptr, SWIGTYPE_p_llvm__Twine NameStr, Instruction InsertBefore) {
    this(bitreaderJNI.new_LoadInst__SWIG_0(Value.getCPtr(Ptr), Ptr, SWIGTYPE_p_llvm__Twine.getCPtr(NameStr), Instruction.getCPtr(InsertBefore), InsertBefore), true);
  }

  public LoadInst(Value Ptr, SWIGTYPE_p_llvm__Twine NameStr, BasicBlock InsertAtEnd) {
    this(bitreaderJNI.new_LoadInst__SWIG_1(Value.getCPtr(Ptr), Ptr, SWIGTYPE_p_llvm__Twine.getCPtr(NameStr), BasicBlock.getCPtr(InsertAtEnd), InsertAtEnd), true);
  }

  public LoadInst(Value Ptr, SWIGTYPE_p_llvm__Twine NameStr, boolean isVolatile, Instruction InsertBefore) {
    this(bitreaderJNI.new_LoadInst__SWIG_2(Value.getCPtr(Ptr), Ptr, SWIGTYPE_p_llvm__Twine.getCPtr(NameStr), isVolatile, Instruction.getCPtr(InsertBefore), InsertBefore), true);
  }

  public LoadInst(Value Ptr, SWIGTYPE_p_llvm__Twine NameStr, boolean isVolatile) {
    this(bitreaderJNI.new_LoadInst__SWIG_3(Value.getCPtr(Ptr), Ptr, SWIGTYPE_p_llvm__Twine.getCPtr(NameStr), isVolatile), true);
  }

  public LoadInst(Value Ptr, SWIGTYPE_p_llvm__Twine NameStr) {
    this(bitreaderJNI.new_LoadInst__SWIG_4(Value.getCPtr(Ptr), Ptr, SWIGTYPE_p_llvm__Twine.getCPtr(NameStr)), true);
  }

  public LoadInst(Value Ptr, SWIGTYPE_p_llvm__Twine NameStr, boolean isVolatile, BasicBlock InsertAtEnd) {
    this(bitreaderJNI.new_LoadInst__SWIG_5(Value.getCPtr(Ptr), Ptr, SWIGTYPE_p_llvm__Twine.getCPtr(NameStr), isVolatile, BasicBlock.getCPtr(InsertAtEnd), InsertAtEnd), true);
  }

  public LoadInst(Value Ptr, SWIGTYPE_p_llvm__Twine NameStr, boolean isVolatile, long Align, Instruction InsertBefore) {
    this(bitreaderJNI.new_LoadInst__SWIG_6(Value.getCPtr(Ptr), Ptr, SWIGTYPE_p_llvm__Twine.getCPtr(NameStr), isVolatile, Align, Instruction.getCPtr(InsertBefore), InsertBefore), true);
  }

  public LoadInst(Value Ptr, SWIGTYPE_p_llvm__Twine NameStr, boolean isVolatile, long Align) {
    this(bitreaderJNI.new_LoadInst__SWIG_7(Value.getCPtr(Ptr), Ptr, SWIGTYPE_p_llvm__Twine.getCPtr(NameStr), isVolatile, Align), true);
  }

  public LoadInst(Value Ptr, SWIGTYPE_p_llvm__Twine NameStr, boolean isVolatile, long Align, BasicBlock InsertAtEnd) {
    this(bitreaderJNI.new_LoadInst__SWIG_8(Value.getCPtr(Ptr), Ptr, SWIGTYPE_p_llvm__Twine.getCPtr(NameStr), isVolatile, Align, BasicBlock.getCPtr(InsertAtEnd), InsertAtEnd), true);
  }

  public LoadInst(Value Ptr, SWIGTYPE_p_llvm__Twine NameStr, boolean isVolatile, long Align, AtomicOrdering Order, SynchronizationScope SynchScope, Instruction InsertBefore) {
    this(bitreaderJNI.new_LoadInst__SWIG_9(Value.getCPtr(Ptr), Ptr, SWIGTYPE_p_llvm__Twine.getCPtr(NameStr), isVolatile, Align, Order.swigValue(), SynchScope.swigValue(), Instruction.getCPtr(InsertBefore), InsertBefore), true);
  }

  public LoadInst(Value Ptr, SWIGTYPE_p_llvm__Twine NameStr, boolean isVolatile, long Align, AtomicOrdering Order, SynchronizationScope SynchScope) {
    this(bitreaderJNI.new_LoadInst__SWIG_10(Value.getCPtr(Ptr), Ptr, SWIGTYPE_p_llvm__Twine.getCPtr(NameStr), isVolatile, Align, Order.swigValue(), SynchScope.swigValue()), true);
  }

  public LoadInst(Value Ptr, SWIGTYPE_p_llvm__Twine NameStr, boolean isVolatile, long Align, AtomicOrdering Order) {
    this(bitreaderJNI.new_LoadInst__SWIG_11(Value.getCPtr(Ptr), Ptr, SWIGTYPE_p_llvm__Twine.getCPtr(NameStr), isVolatile, Align, Order.swigValue()), true);
  }

  public LoadInst(Value Ptr, SWIGTYPE_p_llvm__Twine NameStr, boolean isVolatile, long Align, AtomicOrdering Order, SynchronizationScope SynchScope, BasicBlock InsertAtEnd) {
    this(bitreaderJNI.new_LoadInst__SWIG_12(Value.getCPtr(Ptr), Ptr, SWIGTYPE_p_llvm__Twine.getCPtr(NameStr), isVolatile, Align, Order.swigValue(), SynchScope.swigValue(), BasicBlock.getCPtr(InsertAtEnd), InsertAtEnd), true);
  }

  public LoadInst(Value Ptr, String NameStr, Instruction InsertBefore) {
    this(bitreaderJNI.new_LoadInst__SWIG_13(Value.getCPtr(Ptr), Ptr, NameStr, Instruction.getCPtr(InsertBefore), InsertBefore), true);
  }

  public LoadInst(Value Ptr, String NameStr, BasicBlock InsertAtEnd) {
    this(bitreaderJNI.new_LoadInst__SWIG_14(Value.getCPtr(Ptr), Ptr, NameStr, BasicBlock.getCPtr(InsertAtEnd), InsertAtEnd), true);
  }

  public LoadInst(Value Ptr, String NameStr, boolean isVolatile, Instruction InsertBefore) {
    this(bitreaderJNI.new_LoadInst__SWIG_15(Value.getCPtr(Ptr), Ptr, NameStr, isVolatile, Instruction.getCPtr(InsertBefore), InsertBefore), true);
  }

  public LoadInst(Value Ptr, String NameStr, boolean isVolatile) {
    this(bitreaderJNI.new_LoadInst__SWIG_16(Value.getCPtr(Ptr), Ptr, NameStr, isVolatile), true);
  }

  public LoadInst(Value Ptr, String NameStr) {
    this(bitreaderJNI.new_LoadInst__SWIG_17(Value.getCPtr(Ptr), Ptr, NameStr), true);
  }

  public LoadInst(Value Ptr) {
    this(bitreaderJNI.new_LoadInst__SWIG_18(Value.getCPtr(Ptr), Ptr), true);
  }

  public LoadInst(Value Ptr, String NameStr, boolean isVolatile, BasicBlock InsertAtEnd) {
    this(bitreaderJNI.new_LoadInst__SWIG_19(Value.getCPtr(Ptr), Ptr, NameStr, isVolatile, BasicBlock.getCPtr(InsertAtEnd), InsertAtEnd), true);
  }

  public boolean isVolatile() {
    return bitreaderJNI.LoadInst_isVolatile(swigCPtr, this);
  }

  public void setVolatile(boolean V) {
    bitreaderJNI.LoadInst_setVolatile(swigCPtr, this, V);
  }

  public long getAlignment() {
    return bitreaderJNI.LoadInst_getAlignment(swigCPtr, this);
  }

  public void setAlignment(long Align) {
    bitreaderJNI.LoadInst_setAlignment(swigCPtr, this, Align);
  }

  public AtomicOrdering getOrdering() {
    return AtomicOrdering.swigToEnum(bitreaderJNI.LoadInst_getOrdering(swigCPtr, this));
  }

  public void setOrdering(AtomicOrdering Ordering) {
    bitreaderJNI.LoadInst_setOrdering(swigCPtr, this, Ordering.swigValue());
  }

  public SynchronizationScope getSynchScope() {
    return SynchronizationScope.swigToEnum(bitreaderJNI.LoadInst_getSynchScope(swigCPtr, this));
  }

  public void setSynchScope(SynchronizationScope xthread) {
    bitreaderJNI.LoadInst_setSynchScope(swigCPtr, this, xthread.swigValue());
  }

  public boolean isAtomic() {
    return bitreaderJNI.LoadInst_isAtomic(swigCPtr, this);
  }

  public void setAtomic(AtomicOrdering Ordering, SynchronizationScope SynchScope) {
    bitreaderJNI.LoadInst_setAtomic__SWIG_0(swigCPtr, this, Ordering.swigValue(), SynchScope.swigValue());
  }

  public void setAtomic(AtomicOrdering Ordering) {
    bitreaderJNI.LoadInst_setAtomic__SWIG_1(swigCPtr, this, Ordering.swigValue());
  }

  public boolean isSimple() {
    return bitreaderJNI.LoadInst_isSimple(swigCPtr, this);
  }

  public boolean isUnordered() {
    return bitreaderJNI.LoadInst_isUnordered(swigCPtr, this);
  }

  public Value getPointerOperand() {
    long cPtr = bitreaderJNI.LoadInst_getPointerOperand__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new Value(cPtr, false);
  }

  public static long getPointerOperandIndex() {
    return bitreaderJNI.LoadInst_getPointerOperandIndex();
  }

  public long getPointerAddressSpace() {
    return bitreaderJNI.LoadInst_getPointerAddressSpace(swigCPtr, this);
  }

  public static boolean classof(Instruction I) {
    return bitreaderJNI.LoadInst_classof__SWIG_0(Instruction.getCPtr(I), I);
  }

  public static boolean classof(Value V) {
    return bitreaderJNI.LoadInst_classof__SWIG_1(Value.getCPtr(V), V);
  }

}
