/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package na.okutane.cpp.llvm;

public class MDNode {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected MDNode(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MDNode obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
  }

  public static MDNode get(LLVMContext Context, SWIGTYPE_p_ArrayRefT_llvm__Value_p_t Vals) {
    long cPtr = bitreaderJNI.MDNode_get(LLVMContext.getCPtr(Context), Context, SWIGTYPE_p_ArrayRefT_llvm__Value_p_t.getCPtr(Vals));
    return (cPtr == 0) ? null : new MDNode(cPtr, false);
  }

  public static MDNode getWhenValsUnresolved(LLVMContext Context, SWIGTYPE_p_ArrayRefT_llvm__Value_p_t Vals, boolean isFunctionLocal) {
    long cPtr = bitreaderJNI.MDNode_getWhenValsUnresolved(LLVMContext.getCPtr(Context), Context, SWIGTYPE_p_ArrayRefT_llvm__Value_p_t.getCPtr(Vals), isFunctionLocal);
    return (cPtr == 0) ? null : new MDNode(cPtr, false);
  }

  public static MDNode getIfExists(LLVMContext Context, SWIGTYPE_p_ArrayRefT_llvm__Value_p_t Vals) {
    long cPtr = bitreaderJNI.MDNode_getIfExists(LLVMContext.getCPtr(Context), Context, SWIGTYPE_p_ArrayRefT_llvm__Value_p_t.getCPtr(Vals));
    return (cPtr == 0) ? null : new MDNode(cPtr, false);
  }

  public static MDNode getTemporary(LLVMContext Context, SWIGTYPE_p_ArrayRefT_llvm__Value_p_t Vals) {
    long cPtr = bitreaderJNI.MDNode_getTemporary(LLVMContext.getCPtr(Context), Context, SWIGTYPE_p_ArrayRefT_llvm__Value_p_t.getCPtr(Vals));
    return (cPtr == 0) ? null : new MDNode(cPtr, false);
  }

  public static void deleteTemporary(MDNode N) {
    bitreaderJNI.MDNode_deleteTemporary(MDNode.getCPtr(N), N);
  }

  public void replaceOperandWith(long i, SWIGTYPE_p_llvm__Value NewVal) {
    bitreaderJNI.MDNode_replaceOperandWith(swigCPtr, this, i, SWIGTYPE_p_llvm__Value.getCPtr(NewVal));
  }

  public SWIGTYPE_p_llvm__Value getOperand(long i) {
    long cPtr = bitreaderJNI.MDNode_getOperand(swigCPtr, this, i);
    return (cPtr == 0) ? null : new SWIGTYPE_p_llvm__Value(cPtr, false);
  }

  public long getNumOperands() {
    return bitreaderJNI.MDNode_getNumOperands(swigCPtr, this);
  }

  public boolean isFunctionLocal() {
    return bitreaderJNI.MDNode_isFunctionLocal(swigCPtr, this);
  }

  public Function getFunction() {
    long cPtr = bitreaderJNI.MDNode_getFunction(swigCPtr, this);
    return (cPtr == 0) ? null : new Function(cPtr, false);
  }

  public void Profile(SWIGTYPE_p_FoldingSetNodeID ID) {
    bitreaderJNI.MDNode_Profile(swigCPtr, this, SWIGTYPE_p_FoldingSetNodeID.getCPtr(ID));
  }

  public static boolean classof(SWIGTYPE_p_llvm__Value V) {
    return bitreaderJNI.MDNode_classof(SWIGTYPE_p_llvm__Value.getCPtr(V));
  }

  public static MDNode getMostGenericTBAA(MDNode A, MDNode B) {
    long cPtr = bitreaderJNI.MDNode_getMostGenericTBAA(MDNode.getCPtr(A), A, MDNode.getCPtr(B), B);
    return (cPtr == 0) ? null : new MDNode(cPtr, false);
  }

  public static MDNode getMostGenericFPMath(MDNode A, MDNode B) {
    long cPtr = bitreaderJNI.MDNode_getMostGenericFPMath(MDNode.getCPtr(A), A, MDNode.getCPtr(B), B);
    return (cPtr == 0) ? null : new MDNode(cPtr, false);
  }

  public static MDNode getMostGenericRange(MDNode A, MDNode B) {
    long cPtr = bitreaderJNI.MDNode_getMostGenericRange(MDNode.getCPtr(A), A, MDNode.getCPtr(B), B);
    return (cPtr == 0) ? null : new MDNode(cPtr, false);
  }

}
