/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package na.okutane.cpp.llvm;

public class NamedMDNode {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected NamedMDNode(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NamedMDNode obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bitreaderJNI.delete_NamedMDNode(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void eraseFromParent() {
    bitreaderJNI.NamedMDNode_eraseFromParent(swigCPtr, this);
  }

  public void dropAllReferences() {
    bitreaderJNI.NamedMDNode_dropAllReferences(swigCPtr, this);
  }

  public Module getParent() {
    long cPtr = bitreaderJNI.NamedMDNode_getParent__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new Module(cPtr, false);
  }

  public MDNode getOperand(long i) {
    long cPtr = bitreaderJNI.NamedMDNode_getOperand(swigCPtr, this, i);
    return (cPtr == 0) ? null : new MDNode(cPtr, false);
  }

  public long getNumOperands() {
    return bitreaderJNI.NamedMDNode_getNumOperands(swigCPtr, this);
  }

  public void addOperand(MDNode M) {
    bitreaderJNI.NamedMDNode_addOperand(swigCPtr, this, MDNode.getCPtr(M), M);
  }

  public StringRef getName() {
    return new StringRef(bitreaderJNI.NamedMDNode_getName(swigCPtr, this), true);
  }

  public void print(SWIGTYPE_p_llvm__raw_ostream ROS, SWIGTYPE_p_AssemblyAnnotationWriter AAW) {
    bitreaderJNI.NamedMDNode_print__SWIG_0(swigCPtr, this, SWIGTYPE_p_llvm__raw_ostream.getCPtr(ROS), SWIGTYPE_p_AssemblyAnnotationWriter.getCPtr(AAW));
  }

  public void print(SWIGTYPE_p_llvm__raw_ostream ROS) {
    bitreaderJNI.NamedMDNode_print__SWIG_1(swigCPtr, this, SWIGTYPE_p_llvm__raw_ostream.getCPtr(ROS));
  }

  public void dump() {
    bitreaderJNI.NamedMDNode_dump(swigCPtr, this);
  }

}
