/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package na.okutane.cpp.llvm;

public class PHINode extends Instruction {
  private long swigCPtr;

  protected PHINode(long cPtr, boolean cMemoryOwn) {
    super(bitreaderJNI.PHINode_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PHINode obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bitreaderJNI.delete_PHINode(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static PHINode Create(Type Ty, long NumReservedValues, SWIGTYPE_p_llvm__Twine NameStr, Instruction InsertBefore) {
    long cPtr = bitreaderJNI.PHINode_Create__SWIG_0(Type.getCPtr(Ty), Ty, NumReservedValues, SWIGTYPE_p_llvm__Twine.getCPtr(NameStr), Instruction.getCPtr(InsertBefore), InsertBefore);
    return (cPtr == 0) ? null : new PHINode(cPtr, false);
  }

  public static PHINode Create(Type Ty, long NumReservedValues, SWIGTYPE_p_llvm__Twine NameStr) {
    long cPtr = bitreaderJNI.PHINode_Create__SWIG_1(Type.getCPtr(Ty), Ty, NumReservedValues, SWIGTYPE_p_llvm__Twine.getCPtr(NameStr));
    return (cPtr == 0) ? null : new PHINode(cPtr, false);
  }

  public static PHINode Create(Type Ty, long NumReservedValues) {
    long cPtr = bitreaderJNI.PHINode_Create__SWIG_2(Type.getCPtr(Ty), Ty, NumReservedValues);
    return (cPtr == 0) ? null : new PHINode(cPtr, false);
  }

  public static PHINode Create(Type Ty, long NumReservedValues, SWIGTYPE_p_llvm__Twine NameStr, BasicBlock InsertAtEnd) {
    long cPtr = bitreaderJNI.PHINode_Create__SWIG_3(Type.getCPtr(Ty), Ty, NumReservedValues, SWIGTYPE_p_llvm__Twine.getCPtr(NameStr), BasicBlock.getCPtr(InsertAtEnd), InsertAtEnd);
    return (cPtr == 0) ? null : new PHINode(cPtr, false);
  }

  public SWIGTYPE_p_p_llvm__BasicBlock block_begin() {
    long cPtr = bitreaderJNI.PHINode_block_begin__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_llvm__BasicBlock(cPtr, false);
  }

  public SWIGTYPE_p_p_llvm__BasicBlock block_end() {
    long cPtr = bitreaderJNI.PHINode_block_end__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_llvm__BasicBlock(cPtr, false);
  }

  public long getNumIncomingValues() {
    return bitreaderJNI.PHINode_getNumIncomingValues(swigCPtr, this);
  }

  public Value getIncomingValue(long i) {
    long cPtr = bitreaderJNI.PHINode_getIncomingValue(swigCPtr, this, i);
    return (cPtr == 0) ? null : new Value(cPtr, false);
  }

  public void setIncomingValue(long i, Value V) {
    bitreaderJNI.PHINode_setIncomingValue(swigCPtr, this, i, Value.getCPtr(V), V);
  }

  public static long getOperandNumForIncomingValue(long i) {
    return bitreaderJNI.PHINode_getOperandNumForIncomingValue(i);
  }

  public static long getIncomingValueNumForOperand(long i) {
    return bitreaderJNI.PHINode_getIncomingValueNumForOperand(i);
  }

  public BasicBlock getIncomingBlock(long i) {
    long cPtr = bitreaderJNI.PHINode_getIncomingBlock__SWIG_0(swigCPtr, this, i);
    return (cPtr == 0) ? null : new BasicBlock(cPtr, false);
  }

  public BasicBlock getIncomingBlock(SWIGTYPE_p_Use U) {
    long cPtr = bitreaderJNI.PHINode_getIncomingBlock__SWIG_1(swigCPtr, this, SWIGTYPE_p_Use.getCPtr(U));
    return (cPtr == 0) ? null : new BasicBlock(cPtr, false);
  }

  public void setIncomingBlock(long i, BasicBlock BB) {
    bitreaderJNI.PHINode_setIncomingBlock(swigCPtr, this, i, BasicBlock.getCPtr(BB), BB);
  }

  public void addIncoming(Value V, BasicBlock BB) {
    bitreaderJNI.PHINode_addIncoming(swigCPtr, this, Value.getCPtr(V), V, BasicBlock.getCPtr(BB), BB);
  }

  public Value removeIncomingValue(long Idx, boolean DeletePHIIfEmpty) {
    long cPtr = bitreaderJNI.PHINode_removeIncomingValue__SWIG_0(swigCPtr, this, Idx, DeletePHIIfEmpty);
    return (cPtr == 0) ? null : new Value(cPtr, false);
  }

  public Value removeIncomingValue(long Idx) {
    long cPtr = bitreaderJNI.PHINode_removeIncomingValue__SWIG_1(swigCPtr, this, Idx);
    return (cPtr == 0) ? null : new Value(cPtr, false);
  }

  public Value removeIncomingValue(BasicBlock BB, boolean DeletePHIIfEmpty) {
    long cPtr = bitreaderJNI.PHINode_removeIncomingValue__SWIG_2(swigCPtr, this, BasicBlock.getCPtr(BB), BB, DeletePHIIfEmpty);
    return (cPtr == 0) ? null : new Value(cPtr, false);
  }

  public Value removeIncomingValue(BasicBlock BB) {
    long cPtr = bitreaderJNI.PHINode_removeIncomingValue__SWIG_3(swigCPtr, this, BasicBlock.getCPtr(BB), BB);
    return (cPtr == 0) ? null : new Value(cPtr, false);
  }

  public int getBasicBlockIndex(BasicBlock BB) {
    return bitreaderJNI.PHINode_getBasicBlockIndex(swigCPtr, this, BasicBlock.getCPtr(BB), BB);
  }

  public Value getIncomingValueForBlock(BasicBlock BB) {
    long cPtr = bitreaderJNI.PHINode_getIncomingValueForBlock(swigCPtr, this, BasicBlock.getCPtr(BB), BB);
    return (cPtr == 0) ? null : new Value(cPtr, false);
  }

  public Value hasConstantValue() {
    long cPtr = bitreaderJNI.PHINode_hasConstantValue(swigCPtr, this);
    return (cPtr == 0) ? null : new Value(cPtr, false);
  }

  public static boolean classof(Instruction I) {
    return bitreaderJNI.PHINode_classof__SWIG_0(Instruction.getCPtr(I), I);
  }

  public static boolean classof(Value V) {
    return bitreaderJNI.PHINode_classof__SWIG_1(Value.getCPtr(V), V);
  }

}
