/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package na.okutane.cpp.llvm;

public class SelectInst extends Instruction {
  private long swigCPtr;

  protected SelectInst(long cPtr, boolean cMemoryOwn) {
    super(bitreaderJNI.SelectInst_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SelectInst obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bitreaderJNI.delete_SelectInst(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static SelectInst Create(Value C, Value S1, Value S2, SWIGTYPE_p_llvm__Twine NameStr, Instruction InsertBefore) {
    long cPtr = bitreaderJNI.SelectInst_Create__SWIG_0(Value.getCPtr(C), C, Value.getCPtr(S1), S1, Value.getCPtr(S2), S2, SWIGTYPE_p_llvm__Twine.getCPtr(NameStr), Instruction.getCPtr(InsertBefore), InsertBefore);
    return (cPtr == 0) ? null : new SelectInst(cPtr, false);
  }

  public static SelectInst Create(Value C, Value S1, Value S2, SWIGTYPE_p_llvm__Twine NameStr) {
    long cPtr = bitreaderJNI.SelectInst_Create__SWIG_1(Value.getCPtr(C), C, Value.getCPtr(S1), S1, Value.getCPtr(S2), S2, SWIGTYPE_p_llvm__Twine.getCPtr(NameStr));
    return (cPtr == 0) ? null : new SelectInst(cPtr, false);
  }

  public static SelectInst Create(Value C, Value S1, Value S2) {
    long cPtr = bitreaderJNI.SelectInst_Create__SWIG_2(Value.getCPtr(C), C, Value.getCPtr(S1), S1, Value.getCPtr(S2), S2);
    return (cPtr == 0) ? null : new SelectInst(cPtr, false);
  }

  public static SelectInst Create(Value C, Value S1, Value S2, SWIGTYPE_p_llvm__Twine NameStr, BasicBlock InsertAtEnd) {
    long cPtr = bitreaderJNI.SelectInst_Create__SWIG_3(Value.getCPtr(C), C, Value.getCPtr(S1), S1, Value.getCPtr(S2), S2, SWIGTYPE_p_llvm__Twine.getCPtr(NameStr), BasicBlock.getCPtr(InsertAtEnd), InsertAtEnd);
    return (cPtr == 0) ? null : new SelectInst(cPtr, false);
  }

  public Value getCondition() {
    long cPtr = bitreaderJNI.SelectInst_getCondition__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new Value(cPtr, false);
  }

  public Value getTrueValue() {
    long cPtr = bitreaderJNI.SelectInst_getTrueValue__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new Value(cPtr, false);
  }

  public Value getFalseValue() {
    long cPtr = bitreaderJNI.SelectInst_getFalseValue__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new Value(cPtr, false);
  }

  public static String areInvalidOperands(Value Cond, Value True, Value False) {
    return bitreaderJNI.SelectInst_areInvalidOperands(Value.getCPtr(Cond), Cond, Value.getCPtr(True), True, Value.getCPtr(False), False);
  }

  public Instruction.OtherOps getOpcode() {
    return Instruction.OtherOps.swigToEnum(bitreaderJNI.SelectInst_getOpcode(swigCPtr, this));
  }

  public static boolean classof(Instruction I) {
    return bitreaderJNI.SelectInst_classof__SWIG_0(Instruction.getCPtr(I), I);
  }

  public static boolean classof(Value V) {
    return bitreaderJNI.SelectInst_classof__SWIG_1(Value.getCPtr(V), V);
  }

}
