/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package na.okutane.cpp.llvm;

public class StringRef {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected StringRef(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StringRef obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bitreaderJNI.delete_StringRef(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public StringRef() {
    this(bitreaderJNI.new_StringRef__SWIG_0(), true);
  }

  public StringRef(String Str) {
    this(bitreaderJNI.new_StringRef__SWIG_1(Str), true);
  }

  public StringRef(String data, long length) {
    this(bitreaderJNI.new_StringRef__SWIG_2(data, length), true);
  }

  public String begin() {
    return bitreaderJNI.StringRef_begin(swigCPtr, this);
  }

  public String end() {
    return bitreaderJNI.StringRef_end(swigCPtr, this);
  }

  public String data() {
    return bitreaderJNI.StringRef_data(swigCPtr, this);
  }

  public boolean empty() {
    return bitreaderJNI.StringRef_empty(swigCPtr, this);
  }

  public long size() {
    return bitreaderJNI.StringRef_size(swigCPtr, this);
  }

  public char front() {
    return bitreaderJNI.StringRef_front(swigCPtr, this);
  }

  public char back() {
    return bitreaderJNI.StringRef_back(swigCPtr, this);
  }

  public boolean equals(StringRef RHS) {
    return bitreaderJNI.StringRef_equals(swigCPtr, this, StringRef.getCPtr(RHS), RHS);
  }

  public boolean equals_lower(StringRef RHS) {
    return bitreaderJNI.StringRef_equals_lower(swigCPtr, this, StringRef.getCPtr(RHS), RHS);
  }

  public int compare(StringRef RHS) {
    return bitreaderJNI.StringRef_compare(swigCPtr, this, StringRef.getCPtr(RHS), RHS);
  }

  public int compare_lower(StringRef RHS) {
    return bitreaderJNI.StringRef_compare_lower(swigCPtr, this, StringRef.getCPtr(RHS), RHS);
  }

  public int compare_numeric(StringRef RHS) {
    return bitreaderJNI.StringRef_compare_numeric(swigCPtr, this, StringRef.getCPtr(RHS), RHS);
  }

  public long edit_distance(StringRef Other, boolean AllowReplacements, long MaxEditDistance) {
    return bitreaderJNI.StringRef_edit_distance__SWIG_0(swigCPtr, this, StringRef.getCPtr(Other), Other, AllowReplacements, MaxEditDistance);
  }

  public long edit_distance(StringRef Other, boolean AllowReplacements) {
    return bitreaderJNI.StringRef_edit_distance__SWIG_1(swigCPtr, this, StringRef.getCPtr(Other), Other, AllowReplacements);
  }

  public long edit_distance(StringRef Other) {
    return bitreaderJNI.StringRef_edit_distance__SWIG_2(swigCPtr, this, StringRef.getCPtr(Other), Other);
  }

  public String str() {
    return bitreaderJNI.StringRef_str(swigCPtr, this);
  }

  public boolean startswith(StringRef Prefix) {
    return bitreaderJNI.StringRef_startswith(swigCPtr, this, StringRef.getCPtr(Prefix), Prefix);
  }

  public boolean endswith(StringRef Suffix) {
    return bitreaderJNI.StringRef_endswith(swigCPtr, this, StringRef.getCPtr(Suffix), Suffix);
  }

  public long find(char C, long From) {
    return bitreaderJNI.StringRef_find__SWIG_0(swigCPtr, this, C, From);
  }

  public long find(char C) {
    return bitreaderJNI.StringRef_find__SWIG_1(swigCPtr, this, C);
  }

  public long find(StringRef Str, long From) {
    return bitreaderJNI.StringRef_find__SWIG_2(swigCPtr, this, StringRef.getCPtr(Str), Str, From);
  }

  public long find(StringRef Str) {
    return bitreaderJNI.StringRef_find__SWIG_3(swigCPtr, this, StringRef.getCPtr(Str), Str);
  }

  public long rfind(char C, long From) {
    return bitreaderJNI.StringRef_rfind__SWIG_0(swigCPtr, this, C, From);
  }

  public long rfind(char C) {
    return bitreaderJNI.StringRef_rfind__SWIG_1(swigCPtr, this, C);
  }

  public long rfind(StringRef Str) {
    return bitreaderJNI.StringRef_rfind__SWIG_2(swigCPtr, this, StringRef.getCPtr(Str), Str);
  }

  public long find_first_of(char C, long From) {
    return bitreaderJNI.StringRef_find_first_of__SWIG_0(swigCPtr, this, C, From);
  }

  public long find_first_of(char C) {
    return bitreaderJNI.StringRef_find_first_of__SWIG_1(swigCPtr, this, C);
  }

  public long find_first_of(StringRef Chars, long From) {
    return bitreaderJNI.StringRef_find_first_of__SWIG_2(swigCPtr, this, StringRef.getCPtr(Chars), Chars, From);
  }

  public long find_first_of(StringRef Chars) {
    return bitreaderJNI.StringRef_find_first_of__SWIG_3(swigCPtr, this, StringRef.getCPtr(Chars), Chars);
  }

  public long find_first_not_of(char C, long From) {
    return bitreaderJNI.StringRef_find_first_not_of__SWIG_0(swigCPtr, this, C, From);
  }

  public long find_first_not_of(char C) {
    return bitreaderJNI.StringRef_find_first_not_of__SWIG_1(swigCPtr, this, C);
  }

  public long find_first_not_of(StringRef Chars, long From) {
    return bitreaderJNI.StringRef_find_first_not_of__SWIG_2(swigCPtr, this, StringRef.getCPtr(Chars), Chars, From);
  }

  public long find_first_not_of(StringRef Chars) {
    return bitreaderJNI.StringRef_find_first_not_of__SWIG_3(swigCPtr, this, StringRef.getCPtr(Chars), Chars);
  }

  public long find_last_of(char C, long From) {
    return bitreaderJNI.StringRef_find_last_of__SWIG_0(swigCPtr, this, C, From);
  }

  public long find_last_of(char C) {
    return bitreaderJNI.StringRef_find_last_of__SWIG_1(swigCPtr, this, C);
  }

  public long find_last_of(StringRef Chars, long From) {
    return bitreaderJNI.StringRef_find_last_of__SWIG_2(swigCPtr, this, StringRef.getCPtr(Chars), Chars, From);
  }

  public long find_last_of(StringRef Chars) {
    return bitreaderJNI.StringRef_find_last_of__SWIG_3(swigCPtr, this, StringRef.getCPtr(Chars), Chars);
  }

  public long find_last_not_of(char C, long From) {
    return bitreaderJNI.StringRef_find_last_not_of__SWIG_0(swigCPtr, this, C, From);
  }

  public long find_last_not_of(char C) {
    return bitreaderJNI.StringRef_find_last_not_of__SWIG_1(swigCPtr, this, C);
  }

  public long find_last_not_of(StringRef Chars, long From) {
    return bitreaderJNI.StringRef_find_last_not_of__SWIG_2(swigCPtr, this, StringRef.getCPtr(Chars), Chars, From);
  }

  public long find_last_not_of(StringRef Chars) {
    return bitreaderJNI.StringRef_find_last_not_of__SWIG_3(swigCPtr, this, StringRef.getCPtr(Chars), Chars);
  }

  public long count(char C) {
    return bitreaderJNI.StringRef_count__SWIG_0(swigCPtr, this, C);
  }

  public long count(StringRef Str) {
    return bitreaderJNI.StringRef_count__SWIG_1(swigCPtr, this, StringRef.getCPtr(Str), Str);
  }

  public boolean getAsInteger(long Radix, APInt Result) {
    return bitreaderJNI.StringRef_getAsInteger(swigCPtr, this, Radix, APInt.getCPtr(Result), Result);
  }

  public String lower() {
    return bitreaderJNI.StringRef_lower(swigCPtr, this);
  }

  public String upper() {
    return bitreaderJNI.StringRef_upper(swigCPtr, this);
  }

  public StringRef substr(long Start, long N) {
    return new StringRef(bitreaderJNI.StringRef_substr__SWIG_0(swigCPtr, this, Start, N), true);
  }

  public StringRef substr(long Start) {
    return new StringRef(bitreaderJNI.StringRef_substr__SWIG_1(swigCPtr, this, Start), true);
  }

  public StringRef drop_front(long N) {
    return new StringRef(bitreaderJNI.StringRef_drop_front__SWIG_0(swigCPtr, this, N), true);
  }

  public StringRef drop_front() {
    return new StringRef(bitreaderJNI.StringRef_drop_front__SWIG_1(swigCPtr, this), true);
  }

  public StringRef drop_back(long N) {
    return new StringRef(bitreaderJNI.StringRef_drop_back__SWIG_0(swigCPtr, this, N), true);
  }

  public StringRef drop_back() {
    return new StringRef(bitreaderJNI.StringRef_drop_back__SWIG_1(swigCPtr, this), true);
  }

  public StringRef slice(long Start, long End) {
    return new StringRef(bitreaderJNI.StringRef_slice(swigCPtr, this, Start, End), true);
  }

  public SWIGTYPE_p_std__pairT_llvm__StringRef_llvm__StringRef_t split(char Separator) {
    return new SWIGTYPE_p_std__pairT_llvm__StringRef_llvm__StringRef_t(bitreaderJNI.StringRef_split__SWIG_0(swigCPtr, this, Separator), true);
  }

  public SWIGTYPE_p_std__pairT_llvm__StringRef_llvm__StringRef_t split(StringRef Separator) {
    return new SWIGTYPE_p_std__pairT_llvm__StringRef_llvm__StringRef_t(bitreaderJNI.StringRef_split__SWIG_1(swigCPtr, this, StringRef.getCPtr(Separator), Separator), true);
  }

  public void split(SWIGTYPE_p_llvm__SmallVectorImplT_llvm__StringRef_t A, StringRef Separator, int MaxSplit, boolean KeepEmpty) {
    bitreaderJNI.StringRef_split__SWIG_2(swigCPtr, this, SWIGTYPE_p_llvm__SmallVectorImplT_llvm__StringRef_t.getCPtr(A), StringRef.getCPtr(Separator), Separator, MaxSplit, KeepEmpty);
  }

  public void split(SWIGTYPE_p_llvm__SmallVectorImplT_llvm__StringRef_t A, StringRef Separator, int MaxSplit) {
    bitreaderJNI.StringRef_split__SWIG_3(swigCPtr, this, SWIGTYPE_p_llvm__SmallVectorImplT_llvm__StringRef_t.getCPtr(A), StringRef.getCPtr(Separator), Separator, MaxSplit);
  }

  public void split(SWIGTYPE_p_llvm__SmallVectorImplT_llvm__StringRef_t A, StringRef Separator) {
    bitreaderJNI.StringRef_split__SWIG_4(swigCPtr, this, SWIGTYPE_p_llvm__SmallVectorImplT_llvm__StringRef_t.getCPtr(A), StringRef.getCPtr(Separator), Separator);
  }

  public SWIGTYPE_p_std__pairT_llvm__StringRef_llvm__StringRef_t rsplit(char Separator) {
    return new SWIGTYPE_p_std__pairT_llvm__StringRef_llvm__StringRef_t(bitreaderJNI.StringRef_rsplit(swigCPtr, this, Separator), true);
  }

  public StringRef ltrim(StringRef Chars) {
    return new StringRef(bitreaderJNI.StringRef_ltrim__SWIG_0(swigCPtr, this, StringRef.getCPtr(Chars), Chars), true);
  }

  public StringRef ltrim() {
    return new StringRef(bitreaderJNI.StringRef_ltrim__SWIG_1(swigCPtr, this), true);
  }

  public StringRef rtrim(StringRef Chars) {
    return new StringRef(bitreaderJNI.StringRef_rtrim__SWIG_0(swigCPtr, this, StringRef.getCPtr(Chars), Chars), true);
  }

  public StringRef rtrim() {
    return new StringRef(bitreaderJNI.StringRef_rtrim__SWIG_1(swigCPtr, this), true);
  }

  public StringRef trim(StringRef Chars) {
    return new StringRef(bitreaderJNI.StringRef_trim__SWIG_0(swigCPtr, this, StringRef.getCPtr(Chars), Chars), true);
  }

  public StringRef trim() {
    return new StringRef(bitreaderJNI.StringRef_trim__SWIG_1(swigCPtr, this), true);
  }

  public final static long npos = bitreaderJNI.StringRef_npos_get();
}
