/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package na.okutane.cpp.llvm;

public class SWIGTYPE_m_Module__llvm__iplistT_GlobalAlias_t {
  private String swigCMemberPtr;

  protected SWIGTYPE_m_Module__llvm__iplistT_GlobalAlias_t(String cMemberPtr, boolean futureUse) {
    swigCMemberPtr = cMemberPtr;
  }

  protected SWIGTYPE_m_Module__llvm__iplistT_GlobalAlias_t() {
    swigCMemberPtr = null;
  }

  protected static String getCMemberPtr(SWIGTYPE_m_Module__llvm__iplistT_GlobalAlias_t obj) {
    return obj.swigCMemberPtr;
  }
}

