/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package na.okutane.cpp.llvm;

public class SWIGTYPE_p_f_r_q_const__llvm__SMDiagnostic_p_void_unsigned_int__void {
  private long swigCPtr;

  protected SWIGTYPE_p_f_r_q_const__llvm__SMDiagnostic_p_void_unsigned_int__void(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_f_r_q_const__llvm__SMDiagnostic_p_void_unsigned_int__void() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_f_r_q_const__llvm__SMDiagnostic_p_void_unsigned_int__void obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

