/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package na.okutane.cpp.llvm;

public final class SynchronizationScope {
  public final static SynchronizationScope SingleThread = new SynchronizationScope("SingleThread", bitreaderJNI.SingleThread_get());
  public final static SynchronizationScope CrossThread = new SynchronizationScope("CrossThread", bitreaderJNI.CrossThread_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SynchronizationScope swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SynchronizationScope.class + " with value " + swigValue);
  }

  private SynchronizationScope(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SynchronizationScope(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SynchronizationScope(String swigName, SynchronizationScope swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SynchronizationScope[] swigValues = { SingleThread, CrossThread };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

