/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package na.okutane.cpp.llvm;

public class UndefValue extends Constant {
  private long swigCPtr;

  protected UndefValue(long cPtr, boolean cMemoryOwn) {
    super(bitreaderJNI.UndefValue_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UndefValue obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bitreaderJNI.delete_UndefValue(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static UndefValue get(Type T) {
    long cPtr = bitreaderJNI.UndefValue_get(Type.getCPtr(T), T);
    return (cPtr == 0) ? null : new UndefValue(cPtr, false);
  }

  public UndefValue getSequentialElement() {
    long cPtr = bitreaderJNI.UndefValue_getSequentialElement(swigCPtr, this);
    return (cPtr == 0) ? null : new UndefValue(cPtr, false);
  }

  public UndefValue getStructElement(long Elt) {
    long cPtr = bitreaderJNI.UndefValue_getStructElement(swigCPtr, this, Elt);
    return (cPtr == 0) ? null : new UndefValue(cPtr, false);
  }

  public UndefValue getElementValue(Constant C) {
    long cPtr = bitreaderJNI.UndefValue_getElementValue__SWIG_0(swigCPtr, this, Constant.getCPtr(C), C);
    return (cPtr == 0) ? null : new UndefValue(cPtr, false);
  }

  public UndefValue getElementValue(long Idx) {
    long cPtr = bitreaderJNI.UndefValue_getElementValue__SWIG_1(swigCPtr, this, Idx);
    return (cPtr == 0) ? null : new UndefValue(cPtr, false);
  }

  public void destroyConstant() {
    bitreaderJNI.UndefValue_destroyConstant(swigCPtr, this);
  }

  public static boolean classof(Value V) {
    return bitreaderJNI.UndefValue_classof(Value.getCPtr(V), V);
  }

}
