/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package na.okutane.cpp.llvm;

public class User extends Value {
  private long swigCPtr;

  protected User(long cPtr, boolean cMemoryOwn) {
    super(bitreaderJNI.User_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(User obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bitreaderJNI.delete_User(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Value getOperand(long i) {
    long cPtr = bitreaderJNI.User_getOperand(swigCPtr, this, i);
    return (cPtr == 0) ? null : new Value(cPtr, false);
  }

  public void setOperand(long i, Value Val) {
    bitreaderJNI.User_setOperand(swigCPtr, this, i, Value.getCPtr(Val), Val);
  }

  public SWIGTYPE_p_Use getOperandUse(long i) {
    return new SWIGTYPE_p_Use(bitreaderJNI.User_getOperandUse__SWIG_0(swigCPtr, this, i), false);
  }

  public long getNumOperands() {
    return bitreaderJNI.User_getNumOperands(swigCPtr, this);
  }

  public SWIGTYPE_p_Use op_begin() {
    long cPtr = bitreaderJNI.User_op_begin__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Use(cPtr, false);
  }

  public SWIGTYPE_p_Use op_end() {
    long cPtr = bitreaderJNI.User_op_end__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Use(cPtr, false);
  }

  static public class value_op_iterator {
    private long swigCPtr;
    protected boolean swigCMemOwn;
  
    protected value_op_iterator(long cPtr, boolean cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = cPtr;
    }
  
    protected static long getCPtr(value_op_iterator obj) {
      return (obj == null) ? 0 : obj.swigCPtr;
    }
  
    protected void finalize() {
      delete();
    }
  
    public synchronized void delete() {
      if (swigCPtr != 0) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          bitreaderJNI.delete_User_value_op_iterator(swigCPtr);
        }
        swigCPtr = 0;
      }
    }
  
    public value_op_iterator(SWIGTYPE_p_Use U) {
      this(bitreaderJNI.new_User_value_op_iterator(SWIGTYPE_p_Use.getCPtr(U)), true);
    }
  
    public Value __ref__() {
      long cPtr = bitreaderJNI.User_value_op_iterator___ref__(swigCPtr, this);
      return (cPtr == 0) ? null : new Value(cPtr, false);
    }
  
    public Value __deref__() {
      long cPtr = bitreaderJNI.User_value_op_iterator___deref__(swigCPtr, this);
      return (cPtr == 0) ? null : new Value(cPtr, false);
    }
  
    public void dump() {
      bitreaderJNI.User_value_op_iterator_dump(swigCPtr, this);
    }
  
    public void print(SWIGTYPE_p_llvm__raw_ostream O, SWIGTYPE_p_llvm__AssemblyAnnotationWriter AAW) {
      bitreaderJNI.User_value_op_iterator_print__SWIG_0(swigCPtr, this, SWIGTYPE_p_llvm__raw_ostream.getCPtr(O), SWIGTYPE_p_llvm__AssemblyAnnotationWriter.getCPtr(AAW));
    }
  
    public void print(SWIGTYPE_p_llvm__raw_ostream O) {
      bitreaderJNI.User_value_op_iterator_print__SWIG_1(swigCPtr, this, SWIGTYPE_p_llvm__raw_ostream.getCPtr(O));
    }
  
    public Type getType() {
      long cPtr = bitreaderJNI.User_value_op_iterator_getType(swigCPtr, this);
      return (cPtr == 0) ? null : new Type(cPtr, false);
    }
  
    public LLVMContext getContext() {
      return new LLVMContext(bitreaderJNI.User_value_op_iterator_getContext(swigCPtr, this), false);
    }
  
    public boolean hasName() {
      return bitreaderJNI.User_value_op_iterator_hasName(swigCPtr, this);
    }
  
    public SWIGTYPE_p_llvm__StringMapEntryT_llvm__Value_p_t getValueName() {
      long cPtr = bitreaderJNI.User_value_op_iterator_getValueName(swigCPtr, this);
      return (cPtr == 0) ? null : new SWIGTYPE_p_llvm__StringMapEntryT_llvm__Value_p_t(cPtr, false);
    }
  
    public void setValueName(SWIGTYPE_p_llvm__StringMapEntryT_llvm__Value_p_t VN) {
      bitreaderJNI.User_value_op_iterator_setValueName(swigCPtr, this, SWIGTYPE_p_llvm__StringMapEntryT_llvm__Value_p_t.getCPtr(VN));
    }
  
    public StringRef getName() {
      return new StringRef(bitreaderJNI.User_value_op_iterator_getName(swigCPtr, this), true);
    }
  
    public void setName(SWIGTYPE_p_llvm__Twine Name) {
      bitreaderJNI.User_value_op_iterator_setName(swigCPtr, this, SWIGTYPE_p_llvm__Twine.getCPtr(Name));
    }
  
    public void takeName(Value V) {
      bitreaderJNI.User_value_op_iterator_takeName(swigCPtr, this, Value.getCPtr(V), V);
    }
  
    public void replaceAllUsesWith(Value V) {
      bitreaderJNI.User_value_op_iterator_replaceAllUsesWith(swigCPtr, this, Value.getCPtr(V), V);
    }
  
    public boolean use_empty() {
      return bitreaderJNI.User_value_op_iterator_use_empty(swigCPtr, this);
    }
  
    public SWIGTYPE_p_value_use_iteratorT_llvm__User_t use_begin() {
      return new SWIGTYPE_p_value_use_iteratorT_llvm__User_t(bitreaderJNI.User_value_op_iterator_use_begin__SWIG_0(swigCPtr, this), true);
    }
  
    public SWIGTYPE_p_value_use_iteratorT_llvm__User_t use_end() {
      return new SWIGTYPE_p_value_use_iteratorT_llvm__User_t(bitreaderJNI.User_value_op_iterator_use_end__SWIG_0(swigCPtr, this), true);
    }
  
    public User use_back() {
      long cPtr = bitreaderJNI.User_value_op_iterator_use_back__SWIG_0(swigCPtr, this);
      return (cPtr == 0) ? null : new User(cPtr, false);
    }
  
    public boolean hasOneUse() {
      return bitreaderJNI.User_value_op_iterator_hasOneUse(swigCPtr, this);
    }
  
    public boolean hasNUses(long N) {
      return bitreaderJNI.User_value_op_iterator_hasNUses(swigCPtr, this, N);
    }
  
    public boolean hasNUsesOrMore(long N) {
      return bitreaderJNI.User_value_op_iterator_hasNUsesOrMore(swigCPtr, this, N);
    }
  
    public boolean isUsedInBasicBlock(BasicBlock BB) {
      return bitreaderJNI.User_value_op_iterator_isUsedInBasicBlock(swigCPtr, this, BasicBlock.getCPtr(BB), BB);
    }
  
    public long getNumUses() {
      return bitreaderJNI.User_value_op_iterator_getNumUses(swigCPtr, this);
    }
  
    public void addUse(SWIGTYPE_p_Use U) {
      bitreaderJNI.User_value_op_iterator_addUse(swigCPtr, this, SWIGTYPE_p_Use.getCPtr(U));
    }
  
    public long getValueID() {
      return bitreaderJNI.User_value_op_iterator_getValueID(swigCPtr, this);
    }
  
    public long getRawSubclassOptionalData() {
      return bitreaderJNI.User_value_op_iterator_getRawSubclassOptionalData(swigCPtr, this);
    }
  
    public void clearSubclassOptionalData() {
      bitreaderJNI.User_value_op_iterator_clearSubclassOptionalData(swigCPtr, this);
    }
  
    public boolean hasSameSubclassOptionalData(Value V) {
      return bitreaderJNI.User_value_op_iterator_hasSameSubclassOptionalData(swigCPtr, this, Value.getCPtr(V), V);
    }
  
    public void intersectOptionalDataWith(Value V) {
      bitreaderJNI.User_value_op_iterator_intersectOptionalDataWith(swigCPtr, this, Value.getCPtr(V), V);
    }
  
    public boolean hasValueHandle() {
      return bitreaderJNI.User_value_op_iterator_hasValueHandle(swigCPtr, this);
    }
  
    public Value stripPointerCasts() {
      long cPtr = bitreaderJNI.User_value_op_iterator_stripPointerCasts__SWIG_0(swigCPtr, this);
      return (cPtr == 0) ? null : new Value(cPtr, false);
    }
  
    public Value stripPointerCastsNoFollowAliases() {
      long cPtr = bitreaderJNI.User_value_op_iterator_stripPointerCastsNoFollowAliases__SWIG_0(swigCPtr, this);
      return (cPtr == 0) ? null : new Value(cPtr, false);
    }
  
    public Value stripInBoundsConstantOffsets() {
      long cPtr = bitreaderJNI.User_value_op_iterator_stripInBoundsConstantOffsets__SWIG_0(swigCPtr, this);
      return (cPtr == 0) ? null : new Value(cPtr, false);
    }
  
    public Value stripInBoundsOffsets() {
      long cPtr = bitreaderJNI.User_value_op_iterator_stripInBoundsOffsets__SWIG_0(swigCPtr, this);
      return (cPtr == 0) ? null : new Value(cPtr, false);
    }
  
    public boolean isDereferenceablePointer() {
      return bitreaderJNI.User_value_op_iterator_isDereferenceablePointer(swigCPtr, this);
    }
  
    public Value DoPHITranslation(BasicBlock CurBB, BasicBlock PredBB) {
      long cPtr = bitreaderJNI.User_value_op_iterator_DoPHITranslation__SWIG_0(swigCPtr, this, BasicBlock.getCPtr(CurBB), CurBB, BasicBlock.getCPtr(PredBB), PredBB);
      return (cPtr == 0) ? null : new Value(cPtr, false);
    }
  
    public long getMaximumAlignment() {
      return bitreaderJNI.User_value_op_iterator_MaximumAlignment_get(swigCPtr, this);
    }
  
    public void mutateType(Type Ty) {
      bitreaderJNI.User_value_op_iterator_mutateType(swigCPtr, this, Type.getCPtr(Ty), Ty);
    }
  
    public String toString() {
      return bitreaderJNI.User_value_op_iterator_toString(swigCPtr, this);
    }
  
  }

  public User.value_op_iterator value_op_begin() {
    return new User.value_op_iterator(bitreaderJNI.User_value_op_begin(swigCPtr, this), true);
  }

  public User.value_op_iterator value_op_end() {
    return new User.value_op_iterator(bitreaderJNI.User_value_op_end(swigCPtr, this), true);
  }

  public void dropAllReferences() {
    bitreaderJNI.User_dropAllReferences(swigCPtr, this);
  }

  public void replaceUsesOfWith(Value From, Value To) {
    bitreaderJNI.User_replaceUsesOfWith(swigCPtr, this, Value.getCPtr(From), From, Value.getCPtr(To), To);
  }

  public static boolean classof(Value V) {
    return bitreaderJNI.User_classof(Value.getCPtr(V), V);
  }

}
