/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package na.okutane.cpp.llvm;

public class VAArgInst {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected VAArgInst(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VAArgInst obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        bitreaderJNI.delete_VAArgInst(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VAArgInst(Value List, Type Ty, SWIGTYPE_p_llvm__Twine NameStr, Instruction InsertBefore) {
    this(bitreaderJNI.new_VAArgInst__SWIG_0(Value.getCPtr(List), List, Type.getCPtr(Ty), Ty, SWIGTYPE_p_llvm__Twine.getCPtr(NameStr), Instruction.getCPtr(InsertBefore), InsertBefore), true);
  }

  public VAArgInst(Value List, Type Ty, SWIGTYPE_p_llvm__Twine NameStr) {
    this(bitreaderJNI.new_VAArgInst__SWIG_1(Value.getCPtr(List), List, Type.getCPtr(Ty), Ty, SWIGTYPE_p_llvm__Twine.getCPtr(NameStr)), true);
  }

  public VAArgInst(Value List, Type Ty) {
    this(bitreaderJNI.new_VAArgInst__SWIG_2(Value.getCPtr(List), List, Type.getCPtr(Ty), Ty), true);
  }

  public VAArgInst(Value List, Type Ty, SWIGTYPE_p_llvm__Twine NameStr, BasicBlock InsertAtEnd) {
    this(bitreaderJNI.new_VAArgInst__SWIG_3(Value.getCPtr(List), List, Type.getCPtr(Ty), Ty, SWIGTYPE_p_llvm__Twine.getCPtr(NameStr), BasicBlock.getCPtr(InsertAtEnd), InsertAtEnd), true);
  }

  public Value getPointerOperand() {
    long cPtr = bitreaderJNI.VAArgInst_getPointerOperand__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new Value(cPtr, false);
  }

  public static long getPointerOperandIndex() {
    return bitreaderJNI.VAArgInst_getPointerOperandIndex();
  }

  public static boolean classof(Instruction I) {
    return bitreaderJNI.VAArgInst_classof__SWIG_0(Instruction.getCPtr(I), I);
  }

  public static boolean classof(Value V) {
    return bitreaderJNI.VAArgInst_classof__SWIG_1(Value.getCPtr(V), V);
  }

}
