/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package na.okutane.cpp.llvm;

public final class LLVMThreadLocalMode {
  public final static LLVMThreadLocalMode LLVMNotThreadLocal = new LLVMThreadLocalMode("LLVMNotThreadLocal", bitreaderJNI.LLVMNotThreadLocal_get());
  public final static LLVMThreadLocalMode LLVMGeneralDynamicTLSModel = new LLVMThreadLocalMode("LLVMGeneralDynamicTLSModel");
  public final static LLVMThreadLocalMode LLVMLocalDynamicTLSModel = new LLVMThreadLocalMode("LLVMLocalDynamicTLSModel");
  public final static LLVMThreadLocalMode LLVMInitialExecTLSModel = new LLVMThreadLocalMode("LLVMInitialExecTLSModel");
  public final static LLVMThreadLocalMode LLVMLocalExecTLSModel = new LLVMThreadLocalMode("LLVMLocalExecTLSModel");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static LLVMThreadLocalMode swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + LLVMThreadLocalMode.class + " with value " + swigValue);
  }

  private LLVMThreadLocalMode(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private LLVMThreadLocalMode(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private LLVMThreadLocalMode(String swigName, LLVMThreadLocalMode swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static LLVMThreadLocalMode[] swigValues = { LLVMNotThreadLocal, LLVMGeneralDynamicTLSModel, LLVMLocalDynamicTLSModel, LLVMInitialExecTLSModel, LLVMLocalExecTLSModel };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

