/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package na.okutane.cpp.llvm;

public final class LLVMDLLStorageClass {
  public final static LLVMDLLStorageClass LLVMDefaultStorageClass = new LLVMDLLStorageClass("LLVMDefaultStorageClass", bitreaderJNI.LLVMDefaultStorageClass_get());
  public final static LLVMDLLStorageClass LLVMDLLImportStorageClass = new LLVMDLLStorageClass("LLVMDLLImportStorageClass", bitreaderJNI.LLVMDLLImportStorageClass_get());
  public final static LLVMDLLStorageClass LLVMDLLExportStorageClass = new LLVMDLLStorageClass("LLVMDLLExportStorageClass", bitreaderJNI.LLVMDLLExportStorageClass_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static LLVMDLLStorageClass swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + LLVMDLLStorageClass.class + " with value " + swigValue);
  }

  private LLVMDLLStorageClass(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private LLVMDLLStorageClass(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private LLVMDLLStorageClass(String swigName, LLVMDLLStorageClass swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static LLVMDLLStorageClass[] swigValues = { LLVMDefaultStorageClass, LLVMDLLImportStorageClass, LLVMDLLExportStorageClass };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

