/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package na.okutane.cpp.llvm;

public final class LLVMAttribute {
  public final static LLVMAttribute LLVMZExtAttribute = new LLVMAttribute("LLVMZExtAttribute", bitreaderJNI.LLVMZExtAttribute_get());
  public final static LLVMAttribute LLVMSExtAttribute = new LLVMAttribute("LLVMSExtAttribute", bitreaderJNI.LLVMSExtAttribute_get());
  public final static LLVMAttribute LLVMNoReturnAttribute = new LLVMAttribute("LLVMNoReturnAttribute", bitreaderJNI.LLVMNoReturnAttribute_get());
  public final static LLVMAttribute LLVMInRegAttribute = new LLVMAttribute("LLVMInRegAttribute", bitreaderJNI.LLVMInRegAttribute_get());
  public final static LLVMAttribute LLVMStructRetAttribute = new LLVMAttribute("LLVMStructRetAttribute", bitreaderJNI.LLVMStructRetAttribute_get());
  public final static LLVMAttribute LLVMNoUnwindAttribute = new LLVMAttribute("LLVMNoUnwindAttribute", bitreaderJNI.LLVMNoUnwindAttribute_get());
  public final static LLVMAttribute LLVMNoAliasAttribute = new LLVMAttribute("LLVMNoAliasAttribute", bitreaderJNI.LLVMNoAliasAttribute_get());
  public final static LLVMAttribute LLVMByValAttribute = new LLVMAttribute("LLVMByValAttribute", bitreaderJNI.LLVMByValAttribute_get());
  public final static LLVMAttribute LLVMNestAttribute = new LLVMAttribute("LLVMNestAttribute", bitreaderJNI.LLVMNestAttribute_get());
  public final static LLVMAttribute LLVMReadNoneAttribute = new LLVMAttribute("LLVMReadNoneAttribute", bitreaderJNI.LLVMReadNoneAttribute_get());
  public final static LLVMAttribute LLVMReadOnlyAttribute = new LLVMAttribute("LLVMReadOnlyAttribute", bitreaderJNI.LLVMReadOnlyAttribute_get());
  public final static LLVMAttribute LLVMNoInlineAttribute = new LLVMAttribute("LLVMNoInlineAttribute", bitreaderJNI.LLVMNoInlineAttribute_get());
  public final static LLVMAttribute LLVMAlwaysInlineAttribute = new LLVMAttribute("LLVMAlwaysInlineAttribute", bitreaderJNI.LLVMAlwaysInlineAttribute_get());
  public final static LLVMAttribute LLVMOptimizeForSizeAttribute = new LLVMAttribute("LLVMOptimizeForSizeAttribute", bitreaderJNI.LLVMOptimizeForSizeAttribute_get());
  public final static LLVMAttribute LLVMStackProtectAttribute = new LLVMAttribute("LLVMStackProtectAttribute", bitreaderJNI.LLVMStackProtectAttribute_get());
  public final static LLVMAttribute LLVMStackProtectReqAttribute = new LLVMAttribute("LLVMStackProtectReqAttribute", bitreaderJNI.LLVMStackProtectReqAttribute_get());
  public final static LLVMAttribute LLVMAlignment = new LLVMAttribute("LLVMAlignment", bitreaderJNI.LLVMAlignment_get());
  public final static LLVMAttribute LLVMNoCaptureAttribute = new LLVMAttribute("LLVMNoCaptureAttribute", bitreaderJNI.LLVMNoCaptureAttribute_get());
  public final static LLVMAttribute LLVMNoRedZoneAttribute = new LLVMAttribute("LLVMNoRedZoneAttribute", bitreaderJNI.LLVMNoRedZoneAttribute_get());
  public final static LLVMAttribute LLVMNoImplicitFloatAttribute = new LLVMAttribute("LLVMNoImplicitFloatAttribute", bitreaderJNI.LLVMNoImplicitFloatAttribute_get());
  public final static LLVMAttribute LLVMNakedAttribute = new LLVMAttribute("LLVMNakedAttribute", bitreaderJNI.LLVMNakedAttribute_get());
  public final static LLVMAttribute LLVMInlineHintAttribute = new LLVMAttribute("LLVMInlineHintAttribute", bitreaderJNI.LLVMInlineHintAttribute_get());
  public final static LLVMAttribute LLVMStackAlignment = new LLVMAttribute("LLVMStackAlignment", bitreaderJNI.LLVMStackAlignment_get());
  public final static LLVMAttribute LLVMReturnsTwice = new LLVMAttribute("LLVMReturnsTwice", bitreaderJNI.LLVMReturnsTwice_get());
  public final static LLVMAttribute LLVMUWTable = new LLVMAttribute("LLVMUWTable", bitreaderJNI.LLVMUWTable_get());
  public final static LLVMAttribute LLVMNonLazyBind = new LLVMAttribute("LLVMNonLazyBind", bitreaderJNI.LLVMNonLazyBind_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static LLVMAttribute swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + LLVMAttribute.class + " with value " + swigValue);
  }

  private LLVMAttribute(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private LLVMAttribute(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private LLVMAttribute(String swigName, LLVMAttribute swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static LLVMAttribute[] swigValues = { LLVMZExtAttribute, LLVMSExtAttribute, LLVMNoReturnAttribute, LLVMInRegAttribute, LLVMStructRetAttribute, LLVMNoUnwindAttribute, LLVMNoAliasAttribute, LLVMByValAttribute, LLVMNestAttribute, LLVMReadNoneAttribute, LLVMReadOnlyAttribute, LLVMNoInlineAttribute, LLVMAlwaysInlineAttribute, LLVMOptimizeForSizeAttribute, LLVMStackProtectAttribute, LLVMStackProtectReqAttribute, LLVMAlignment, LLVMNoCaptureAttribute, LLVMNoRedZoneAttribute, LLVMNoImplicitFloatAttribute, LLVMNakedAttribute, LLVMInlineHintAttribute, LLVMStackAlignment, LLVMReturnsTwice, LLVMUWTable, LLVMNonLazyBind };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

