/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package na.okutane.cpp.llvm;

public final class LLVMDiagnosticSeverity {
  public final static LLVMDiagnosticSeverity LLVMDSError = new LLVMDiagnosticSeverity("LLVMDSError");
  public final static LLVMDiagnosticSeverity LLVMDSWarning = new LLVMDiagnosticSeverity("LLVMDSWarning");
  public final static LLVMDiagnosticSeverity LLVMDSRemark = new LLVMDiagnosticSeverity("LLVMDSRemark");
  public final static LLVMDiagnosticSeverity LLVMDSNote = new LLVMDiagnosticSeverity("LLVMDSNote");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static LLVMDiagnosticSeverity swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + LLVMDiagnosticSeverity.class + " with value " + swigValue);
  }

  private LLVMDiagnosticSeverity(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private LLVMDiagnosticSeverity(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private LLVMDiagnosticSeverity(String swigName, LLVMDiagnosticSeverity swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static LLVMDiagnosticSeverity[] swigValues = { LLVMDSError, LLVMDSWarning, LLVMDSRemark, LLVMDSNote };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

